import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('sr'),
    Locale('hr'),
    Locale('bs'),
    Locale('mk'),
    Locale('de'),
    Locale('en'),
    Locale('bg'),
  ];

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings) ??
      const AppStrings(Locale('sr'));

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['sr']!)[key] ??
      _values['sr']![key] ??
      key;

  String remaining(int value) =>
      text('remaining').replaceFirst('{count}', value.toString());

  String category(String key) =>
      (_categories[locale.languageCode] ?? _categories['sr']!)[key] ??
      _categories['sr']![key] ??
      key;

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  static const _categories = <String, Map<String, String>>{
    'sr': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Stanodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanska služba',
      'sozialamt': 'Socijalna služba',
      'jugendamt': 'Služba za mlade i porodicu',
      'wohngeldstelle': 'Služba za Wohngeld',
      'bafoegAmt': 'BAföG služba',
      'rentenversicherung': 'Penzijsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Snabdevač energijom',
      'debtCollection': 'Inkaso',
      'police': 'Policija / tužilaštvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'hr': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Najmodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanski ured',
      'sozialamt': 'Socijalni ured',
      'jugendamt': 'Ured za mlade i obitelj',
      'wohngeldstelle': 'Ured za Wohngeld',
      'bafoegAmt': 'BAföG ured',
      'rentenversicherung': 'Mirovinsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Opskrbljivač energijom',
      'debtCollection': 'Naplata potraživanja',
      'police': 'Policija / tužiteljstvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'bs': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Stanodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanska služba',
      'sozialamt': 'Socijalna služba',
      'jugendamt': 'Služba za mlade i porodicu',
      'wohngeldstelle': 'Služba za Wohngeld',
      'bafoegAmt': 'BAföG služba',
      'rentenversicherung': 'Penzijsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Snabdjevač energijom',
      'debtCollection': 'Inkaso',
      'police': 'Policija / tužilaštvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'mk': {
      'finanzamt': 'Даночна управа',
      'krankenkasse': 'Здравствено осигурување',
      'jobcenter': 'Jobcenter',
      'bank': 'Банка',
      'insurance': 'Осигурување',
      'telecom': 'Телеком',
      'employer': 'Работодавач',
      'landlord': 'Сопственик на стан',
      'school': 'Училиште',
      'kindergarten': 'Градинка',
      'court': 'Суд',
      'familienkasse': 'Familienkasse / детски додаток',
      'agenturFuerArbeit': 'Агенција за вработување',
      'auslaenderbehoerde': 'Служба за странци',
      'buergeramt': 'Граѓанска служба',
      'sozialamt': 'Социјална служба',
      'jugendamt': 'Служба за млади и семејство',
      'wohngeldstelle': 'Служба за Wohngeld',
      'bafoegAmt': 'BAföG служба',
      'rentenversicherung': 'Пензиско осигурување',
      'rundfunkbeitrag': 'Радиодифузна такса',
      'energy': 'Снабдувач со енергија',
      'debtCollection': 'Наплата на долг',
      'police': 'Полиција / обвинителство',
      'customs': 'Царина (Zoll)',
      'other': 'Друго',
    },
    'de': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Krankenkasse',
      'jobcenter': 'Jobcenter',
      'bank': 'Bank',
      'insurance': 'Versicherung',
      'telecom': 'Telekommunikation',
      'employer': 'Arbeitgeber',
      'landlord': 'Vermieter',
      'school': 'Schule',
      'kindergarten': 'Kindergarten',
      'court': 'Gericht',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agentur für Arbeit',
      'auslaenderbehoerde': 'Ausländerbehörde',
      'buergeramt': 'Bürgeramt',
      'sozialamt': 'Sozialamt',
      'jugendamt': 'Jugendamt',
      'wohngeldstelle': 'Wohngeldstelle',
      'bafoegAmt': 'BAföG-Amt',
      'rentenversicherung': 'Rentenversicherung',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Energieversorger',
      'debtCollection': 'Inkasso',
      'police': 'Polizei / Staatsanwaltschaft',
      'customs': 'Zoll',
      'other': 'Sonstiges',
    },
    'en': {
      'finanzamt': 'Tax office',
      'krankenkasse': 'Health insurer',
      'jobcenter': 'Jobcenter',
      'bank': 'Bank',
      'insurance': 'Insurance',
      'telecom': 'Telecom',
      'employer': 'Employer',
      'landlord': 'Landlord',
      'school': 'School',
      'kindergarten': 'Kindergarten',
      'court': 'Court',
      'familienkasse': 'Familienkasse / child benefit',
      'agenturFuerArbeit': 'Employment Agency',
      'auslaenderbehoerde': 'Immigration authority',
      'buergeramt': 'Citizens’ office',
      'sozialamt': 'Social welfare office',
      'jugendamt': 'Youth welfare office',
      'wohngeldstelle': 'Housing benefit office',
      'bafoegAmt': 'BAföG office',
      'rentenversicherung': 'Pension insurance',
      'rundfunkbeitrag': 'Broadcasting contribution',
      'energy': 'Energy supplier',
      'debtCollection': 'Debt collection',
      'police': 'Police / prosecution office',
      'customs': 'Customs (Zoll)',
      'other': 'Other',
    },
    'bg': {
      'finanzamt': 'Данъчна служба',
      'krankenkasse': 'Здравно осигуряване',
      'jobcenter': 'Jobcenter',
      'bank': 'Банка',
      'insurance': 'Застраховане',
      'telecom': 'Телеком',
      'employer': 'Работодател',
      'landlord': 'Наемодател',
      'school': 'Училище',
      'kindergarten': 'Детска градина',
      'court': 'Съд',
      'familienkasse': 'Familienkasse / детски надбавки',
      'agenturFuerArbeit': 'Агенция по заетостта',
      'auslaenderbehoerde': 'Служба за чужденци',
      'buergeramt': 'Гражданска служба',
      'sozialamt': 'Социална служба',
      'jugendamt': 'Служба за младежи и семейство',
      'wohngeldstelle': 'Служба за Wohngeld',
      'bafoegAmt': 'BAföG служба',
      'rentenversicherung': 'Пенсионно осигуряване',
      'rundfunkbeitrag': 'Такса за обществено излъчване',
      'energy': 'Доставчик на енергия',
      'debtCollection': 'Събиране на вземания',
      'police': 'Полиция / прокуратура',
      'customs': 'Митници (Zoll)',
      'other': 'Друго',
    },
  };

  static const _values = <String, Map<String, String>>{
    'sr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumite nemačka pisma, na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 3 probne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Poslednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili kreirajte nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Kreiraj nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi sa Google',
      'continueApple': 'Nastavi sa Apple',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Preferirani jezik',
      'country': 'Zemlja porekla',
      'addCountry': 'Dodajte zemlju porekla',
      'signInForProfile': 'Prijavite se da biste sačuvali profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu saglasnost samo OCR tekst se šalje OpenAI-ju za trenutnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst sa pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografišite dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o poslednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografiši nemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propusti rokove',
      'onboardDeadlineBody': 'Dobijte podsetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovo.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađen iznos',
      'nextSteps': 'Šta sada da uradite',
      'originalMissing': 'Originalni dokument nije sačuvan uz analizu.',
      'openOriginal': 'Otvori ili preuzmi original',
      'generateReply': 'Generiši odgovor',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Predlog odgovora',
      'formalReply': 'Formalni nemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-mail',
      'savePdf': 'Sačuvaj PDF',
      'archiveSubtitle': 'Vaša pisma su organizovana po statusu i kategoriji.',
      'deleteDocument': 'Obriši dokument',
      'deleteDocumentBody':
          'Original, OCR tekst i analiza biće trajno obrisani samo sa ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Obriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analize, odgovori i podsetnici uz odgovornu upotrebu',
      'freeBetaActive': 'Besplatna beta: OpenAI analiza uz zaštitne limite.',
      'freeBetaTitle': 'BriefAI besplatna beta',
      'freeBetaBody':
          'Plaćanje je isključeno dok testiramo kvalitet. Originalni dokumenti ostaju lokalno; uz saglasnost se šalje samo OCR tekst za trenutni OpenAI zahtev.',
      'privacyPolicy': 'Politika privatnosti',
      'terms': 'Uslovi korišćenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle':
          'Lokalni JSON izvoz profila, analiza i originalnih dokumenata',
      'deleteLocal': 'Obriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše dokumente samo iz anonimne arhive',
      'deleteLocalBody':
          'Originalni dokumenti, OCR tekst, analize i podsetnici biće trajno obrisani sa ovog uređaja.',
      'deleteAccount': 'Trajno obriši nalog',
      'deleteAccountQuestion': 'Obrisati nalog?',
      'deleteAccountBody':
          'Ova radnja trajno briše lokalne dokumente, analize, podsetnike i korisnički nalog.',
      'prepareExport': 'Pripremam privatni izvoz podataka…',
      'exportUnavailable': 'Izvoz podataka trenutno nije dostupan.',
      'choosePlan': 'Izaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '3 probne analize ukupno',
      'premiumFeature1': 'Analize uz zaštitu odgovorne upotrebe',
      'premiumFeature2': 'AI odgovori i prevodi',
      'premiumFeature3': 'Arhiva i podsetnici',
      'proFeature1': 'Za porodice i male firme',
      'proFeature2': 'Sve iz Premium paketa i viši prag upotrebe',
      'restorePurchases': 'Vrati kupovine',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Izaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'Rešavam',
      'doneStatus': 'Završeno',
      'save': 'Sačuvaj',
      'lastUpdated': 'Poslednja izmena: 26. jul 2026.',
      'dataController': 'Vlasnik podataka',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni bezbedno',
      'skip': 'Preskoči',
    },
    'hr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 3 probne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate spremljenih pisama.',
      'accountCta': 'Prijavite se ili izradite račun',
      'accountCtaSubtitle': 'Račun štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Izradi račun',
      'secureLetters': 'Vaš račun, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'E-pošta',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate račun? Prijavite se',
      'needAccount': 'Nemate račun? Registrirajte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja podrijetla',
      'addCountry': 'Dodajte zemlju podrijetla',
      'signInForProfile': 'Prijavite se za spremanje profila',
      'signOut': 'Odjava',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu privolu samo OCR tekst šalje se OpenAI-ju za trenutačnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografirajte dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Pozdrav! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografirajte njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava značenje',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Primajte podsjetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspjela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovno.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađeni iznos',
      'nextSteps': 'Što sada trebate učiniti',
      'originalMissing': 'Izvorni dokument nije spremljen uz analizu.',
      'openOriginal': 'Otvori ili preuzmi izvornik',
      'generateReply': 'Generiraj odgovor',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Prijedlog odgovora',
      'formalReply': 'Formalni njemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-poštu',
      'savePdf': 'Spremi PDF',
      'archiveSubtitle': 'Vaša su pisma organizirana po statusu i kategoriji.',
      'deleteDocument': 'Izbriši dokument',
      'deleteDocumentBody':
          'Izvornik, OCR tekst i analiza trajno će se izbrisati samo s ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Izbriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analize, odgovori i podsjetnici uz odgovornu uporabu',
      'freeBetaActive': 'Besplatna beta: OpenAI analiza uz zaštitne limite.',
      'freeBetaTitle': 'BriefAI besplatna beta',
      'freeBetaBody':
          'Plaćanje je isključeno tijekom testiranja kvalitete. Izvorni dokumenti ostaju lokalno; uz privolu se šalje samo OCR tekst za trenutačni OpenAI zahtjev.',
      'privacyPolicy': 'Pravila privatnosti',
      'terms': 'Uvjeti korištenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle': 'Lokalni JSON izvoz profila, analiza i dokumenata',
      'deleteLocal': 'Izbriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše samo anonimnu arhivu',
      'deleteLocalBody':
          'Dokumenti, OCR tekst, analize i podsjetnici trajno će se izbrisati s uređaja.',
      'deleteAccount': 'Trajno izbriši račun',
      'deleteAccountQuestion': 'Izbrisati račun?',
      'deleteAccountBody':
          'Time se trajno brišu lokalni dokumenti, analize, podsjetnici i račun.',
      'prepareExport': 'Pripremam privatni izvoz…',
      'exportUnavailable': 'Izvoz trenutačno nije dostupan.',
      'choosePlan': 'Odaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '3 probne analize ukupno',
      'premiumFeature1': 'Analize uz zaštitu odgovorne uporabe',
      'premiumFeature2': 'AI odgovori i prijevodi',
      'premiumFeature3': 'Arhiva i podsjetnici',
      'proFeature1': 'Za obitelji i male tvrtke',
      'proFeature2': 'Sve iz Premium paketa i viši prag uporabe',
      'restorePurchases': 'Vrati kupnje',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Odaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'U tijeku',
      'doneStatus': 'Završeno',
      'save': 'Spremi',
      'lastUpdated': 'Posljednja izmjena: 26. srpnja 2026.',
      'dataController': 'Voditelj obrade',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'bs': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 3 probne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili napravite nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Napravi nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja porijekla',
      'addCountry': 'Dodajte zemlju porijekla',
      'signInForProfile': 'Prijavite se da sačuvate profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu saglasnost samo OCR tekst se šalje OpenAI-ju za trenutnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografišite dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografišite njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Dobijte podsjetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspjela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovo.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađen iznos',
      'nextSteps': 'Šta sada trebate uraditi',
      'originalMissing': 'Originalni dokument nije sačuvan uz analizu.',
      'openOriginal': 'Otvori ili preuzmi original',
      'generateReply': 'Generiši odgovor',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Prijedlog odgovora',
      'formalReply': 'Formalni njemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-mail',
      'savePdf': 'Sačuvaj PDF',
      'archiveSubtitle': 'Vaša pisma su organizovana po statusu i kategoriji.',
      'deleteDocument': 'Obriši dokument',
      'deleteDocumentBody':
          'Original, OCR tekst i analiza trajno će se obrisati samo sa ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Obriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle':
          'Analize, odgovori i podsjetnici uz odgovornu upotrebu',
      'freeBetaActive': 'Besplatna beta: OpenAI analiza uz zaštitne limite.',
      'freeBetaTitle': 'BriefAI besplatna beta',
      'freeBetaBody':
          'Plaćanje je isključeno dok testiramo kvalitet. Originalni dokumenti ostaju lokalno; uz saglasnost se šalje samo OCR tekst za trenutni OpenAI zahtjev.',
      'privacyPolicy': 'Politika privatnosti',
      'terms': 'Uslovi korištenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle': 'Lokalni JSON izvoz profila, analiza i dokumenata',
      'deleteLocal': 'Obriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše samo anonimnu arhivu',
      'deleteLocalBody':
          'Dokumenti, OCR tekst, analize i podsjetnici trajno će se obrisati sa uređaja.',
      'deleteAccount': 'Trajno obriši nalog',
      'deleteAccountQuestion': 'Obrisati nalog?',
      'deleteAccountBody':
          'Ovo trajno briše lokalne dokumente, analize, podsjetnike i nalog.',
      'prepareExport': 'Pripremam privatni izvoz…',
      'exportUnavailable': 'Izvoz trenutno nije dostupan.',
      'choosePlan': 'Izaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '3 probne analize ukupno',
      'premiumFeature1': 'Analize uz zaštitu odgovorne upotrebe',
      'premiumFeature2': 'AI odgovori i prevodi',
      'premiumFeature3': 'Arhiva i podsjetnici',
      'proFeature1': 'Za porodice i male firme',
      'proFeature2': 'Sve iz Premium paketa i viši prag upotrebe',
      'restorePurchases': 'Vrati kupovine',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Izaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'Rješavam',
      'doneStatus': 'Završeno',
      'save': 'Sačuvaj',
      'lastUpdated': 'Posljednja izmjena: 26. juli 2026.',
      'dataController': 'Kontrolor podataka',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'mk': {
      'home': 'Почетна',
      'archive': 'Архива',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добредојдовте',
      'homeSubtitle': 'Разберете ги германските писма на вашиот јазик.',
      'analyzeNew': 'Анализирај ново писмо',
      'remaining': 'Преостануваат {count} од 3 пробни анализи.',
      'unlimited': 'Premium анализите се активни.',
      'addDocument': 'Додај документ',
      'activatePremium': 'Активирај Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Сè уште немате зачувани писма.',
      'accountCta': 'Најавете се или креирајте сметка',
      'accountCtaSubtitle': 'Сметката ги штити планот и локалната архива.',
      'appLanguage': 'Јазик на апликацијата',
      'signIn': 'Најава',
      'createAccount': 'Креирај сметка',
      'secureLetters': 'Вашата сметка, план и локална архива се одвоени.',
      'email': 'Е-пошта',
      'password': 'Лозинка (најмалку 6 знаци)',
      'continueGoogle': 'Продолжи со Google',
      'continueApple': 'Продолжи со Apple',
      'haveAccount': 'Имате сметка? Најавете се',
      'needAccount': 'Немате сметка? Регистрирајте се',
      'signInFailed': 'Најавата не успеа',
      'myProfile': 'Мој профил',
      'preferredLanguage': 'Претпочитан јазик',
      'country': 'Земја на потекло',
      'addCountry': 'Додајте земја на потекло',
      'signInForProfile': 'Најавете се за да го зачувате профилот',
      'signOut': 'Одјави се',
      'uploadDocument': 'Вчитајте документ',
      'localProcessing':
          'Сликата/PDF и архивата остануваат локално. Со ваша согласност само OCR текстот се испраќа до OpenAI за тековната анализа.',
      'camera': 'Камера',
      'gallery': 'Галерија',
      'pdfImage': 'PDF или слика',
      'letterText': 'Текст од писмото',
      'ocrReading': 'Го препознавам текстот локално…',
      'loadingImage': 'Ја вчитувам фотографијата…',
      'ocrReady': 'Документот е вчитан и текстот е препознаен.',
      'ocrNotReady': 'Текстот сè уште не е препознаен.',
      'photoReadyForAnalysis':
          'Фотографијата е вчитана. Притиснете „Анализирај писмо“.',
      'ocrFailed': 'Документот не е препознаен',
      'enterTextFirst': 'Фотографирајте документ или внесете текст.',
      'analyzeLetter': 'Анализирај писмо',
      'processing': 'AI обработува…',
      'newAnalysis': 'Нова анализа',
      'assistantTitle': 'AI асистент',
      'assistantHello': 'Здраво! Прашајте ме за последното анализирано писмо.',
      'assistantHint': 'На пр. Кој е рокот?',
      'onboardPhoto': 'Фотографирајте германско писмо',
      'onboardPhotoBody': 'Сликајте документ или вчитајте PDF и слика.',
      'onboardAi': 'AI објаснува што значи',
      'onboardAiBody': 'Јасно објаснување на вашиот јазик.',
      'onboardDeadline': 'Не пропуштајте рокови',
      'onboardDeadlineBody': 'Добивајте потсетници за важни датуми.',
      'analysisFailed': 'Анализата не успеа',
      'sessionExpired': 'Сесијата истече. Најавете се повторно.',
      'tryAgain': 'Обидете се повторно.',
      'resultTitle': 'Резултат од анализата',
      'simpleExplanation': 'Едноставно објаснување',
      'category': 'Категорија',
      'deadline': 'Рок',
      'amount': 'Пронајден износ',
      'nextSteps': 'Што треба да направите сега',
      'originalMissing': 'Оригиналниот документ не е зачуван со анализата.',
      'openOriginal': 'Отвори или преземи оригинал',
      'generateReply': 'Генерирај одговор',
      'finishHome': 'Заврши и оди на почетна',
      'replyTitle': 'Предлог-одговор',
      'formalReply': 'Формален одговор на германски',
      'letter': 'Писмо',
      'responseUnavailable': 'Одговорот не е достапен',
      'replyCopied': 'Одговорот е копиран.',
      'copyReply': 'Копирај одговор',
      'sendEmail': 'Испрати е-пошта',
      'savePdf': 'Зачувај PDF',
      'archiveSubtitle': 'Вашите писма се организирани по статус и категорија.',
      'deleteDocument': 'Избриши документ',
      'deleteDocumentBody':
          'Оригиналот, OCR текстот и анализата трајно ќе се избришат само од овој уред.',
      'cancel': 'Откажи',
      'delete': 'Избриши',
      'name': 'Име',
      'addName': 'Додајте име',
      'premiumActive': 'Premium е активен',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Анализи, одговори и потсетници со одговорна употреба',
      'freeBetaActive': 'Бесплатна бета: OpenAI анализа со заштитни лимити.',
      'freeBetaTitle': 'BriefAI бесплатна бета',
      'freeBetaBody':
          'Плаќањето е исклучено додека го тестираме квалитетот. Оригиналите остануваат локално; со согласност се испраќа само OCR текстот.',
      'privacyPolicy': 'Политика за приватност',
      'terms': 'Услови за користење',
      'exportData': 'Преземи ги моите податоци',
      'exportSubtitle': 'Локален JSON извоз на профил, анализи и документи',
      'deleteLocal': 'Избриши локална архива',
      'deleteLocalSubtitle': 'Ги брише документите само од анонимната архива',
      'deleteLocalBody':
          'Документите, OCR текстот, анализите и потсетниците трајно ќе се избришат од уредот.',
      'deleteAccount': 'Трајно избриши сметка',
      'deleteAccountQuestion': 'Да се избрише сметката?',
      'deleteAccountBody':
          'Ова трајно ги брише локалните документи, анализи, потсетници и сметката.',
      'prepareExport': 'Подготвувам приватен извоз…',
      'exportUnavailable': 'Извозот моментално не е достапен.',
      'choosePlan': 'Изберете план',
      'planTagline': 'Повеќе сигурност, помалку стрес.',
      'freeFeature': 'Вкупно 3 пробни анализи',
      'premiumFeature1': 'Анализи со заштита на одговорна употреба',
      'premiumFeature2': 'AI одговори и преводи',
      'premiumFeature3': 'Архива и потсетници',
      'proFeature1': 'За семејства и мали фирми',
      'proFeature2': 'Сè од Premium и повисок праг',
      'restorePurchases': 'Врати купувања',
      'manageSubscription': 'Управувај или откажи претплата',
      'choosePlanButton': 'Избери план',
      'newStatus': 'Ново',
      'progressStatus': 'Во тек',
      'doneStatus': 'Завршено',
      'save': 'Зачувај',
      'lastUpdated': 'Последна измена: 26 јули 2026.',
      'dataController': 'Контролор на податоци',
      'contact': 'Контакт',
      'address': 'Адреса',
      'next': 'Продолжи',
      'start': 'Започни безбедно',
      'skip': 'Прескокни',
    },
    'de': {
      'home': 'Start',
      'archive': 'Archiv',
      'assistant': 'Assistent',
      'profile': 'Profil',
      'welcome': 'Willkommen',
      'homeSubtitle': 'Verstehen Sie deutsche Briefe in Ihrer Sprache.',
      'analyzeNew': 'Neuen Brief analysieren',
      'remaining': 'Noch {count} von 3 Testanalysen.',
      'unlimited': 'Premium-Analysen sind aktiv.',
      'addDocument': 'Dokument hinzufügen',
      'activatePremium': 'Premium aktivieren',
      'recentLetters': 'Letzte Briefe',
      'emptyLetters': 'Noch keine Briefe gespeichert.',
      'accountCta': 'Anmelden oder Konto erstellen',
      'accountCtaSubtitle':
          'Ihr Konto schützt Tarif und getrenntes lokales Archiv.',
      'appLanguage': 'App-Sprache',
      'signIn': 'Anmelden',
      'createAccount': 'Konto erstellen',
      'secureLetters': 'Konto, Tarif und lokales Archiv bleiben getrennt.',
      'email': 'E-Mail',
      'password': 'Passwort (mindestens 6 Zeichen)',
      'continueGoogle': 'Mit Google fortfahren',
      'continueApple': 'Mit Apple fortfahren',
      'haveAccount': 'Bereits registriert? Anmelden',
      'needAccount': 'Noch kein Konto? Registrieren',
      'signInFailed': 'Anmeldung fehlgeschlagen',
      'myProfile': 'Mein Profil',
      'preferredLanguage': 'Bevorzugte Sprache',
      'country': 'Herkunftsland',
      'addCountry': 'Herkunftsland hinzufügen',
      'signInForProfile': 'Zum Speichern des Profils anmelden',
      'signOut': 'Abmelden',
      'uploadDocument': 'Dokument hochladen',
      'localProcessing':
          'Bild/PDF und Archiv bleiben lokal. Mit Ihrer Einwilligung wird nur der OCR-Text für die aktuelle Analyse an OpenAI gesendet.',
      'camera': 'Kamera',
      'gallery': 'Galerie',
      'pdfImage': 'PDF oder Bild',
      'letterText': 'Brieftext',
      'ocrReading': 'Text wird lokal erkannt…',
      'loadingImage': 'Foto wird geladen…',
      'ocrReady': 'Dokument geladen und Text erkannt.',
      'ocrNotReady': 'Text wurde noch nicht erkannt.',
      'photoReadyForAnalysis':
          'Das Foto ist geladen. Tippen Sie auf „Schreiben analysieren“.',
      'ocrFailed': 'Dokument wurde nicht erkannt',
      'enterTextFirst': 'Dokument fotografieren oder Brieftext eingeben.',
      'analyzeLetter': 'Brief analysieren',
      'processing': 'KI verarbeitet…',
      'newAnalysis': 'Neue Analyse',
      'assistantTitle': 'KI-Assistent',
      'assistantHello':
          'Hallo! Fragen Sie mich zum zuletzt analysierten Brief.',
      'assistantHint': 'Z. B. Welche Frist gilt?',
      'onboardPhoto': 'Deutschen Brief fotografieren',
      'onboardPhotoBody': 'Dokument aufnehmen oder PDF/Bild laden.',
      'onboardAi': 'KI erklärt die Bedeutung',
      'onboardAiBody': 'Klare Erklärung in Ihrer Sprache.',
      'onboardDeadline': 'Keine Frist verpassen',
      'onboardDeadlineBody': 'Erinnerungen für wichtige Termine erhalten.',
      'analysisFailed': 'Analyse fehlgeschlagen',
      'sessionExpired': 'Die Sitzung ist abgelaufen. Bitte erneut anmelden.',
      'tryAgain': 'Bitte versuchen Sie es erneut.',
      'resultTitle': 'Analyseergebnis',
      'simpleExplanation': 'Einfache Erklärung',
      'category': 'Kategorie',
      'deadline': 'Frist',
      'amount': 'Gefundener Betrag',
      'nextSteps': 'Was Sie jetzt tun sollten',
      'originalMissing': 'Das Originaldokument wurde nicht gespeichert.',
      'openOriginal': 'Original öffnen oder herunterladen',
      'generateReply': 'Antwort erstellen',
      'finishHome': 'Fertig und zur Startseite',
      'replyTitle': 'Antwortvorschlag',
      'formalReply': 'Formelle deutsche Antwort',
      'letter': 'Brief',
      'responseUnavailable': 'Antwort nicht verfügbar',
      'replyCopied': 'Antwort kopiert.',
      'copyReply': 'Antwort kopieren',
      'sendEmail': 'E-Mail senden',
      'savePdf': 'PDF speichern',
      'archiveSubtitle': 'Ihre Briefe sind nach Status und Kategorie geordnet.',
      'deleteDocument': 'Dokument löschen',
      'deleteDocumentBody':
          'Original, OCR-Text und Analyse werden nur auf diesem Gerät dauerhaft gelöscht.',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'name': 'Name',
      'addName': 'Name hinzufügen',
      'premiumActive': 'Premium ist aktiv',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle':
          'Analysen, Antworten und Erinnerungen bei fairer Nutzung',
      'freeBetaActive': 'Kostenlose Beta: OpenAI-Analyse mit Schutzlimits.',
      'freeBetaTitle': 'Kostenlose BriefAI-Beta',
      'freeBetaBody':
          'Zahlungen sind während des Qualitätstests deaktiviert. Originale bleiben lokal; mit Einwilligung wird nur OCR-Text für die aktuelle OpenAI-Anfrage gesendet.',
      'privacyPolicy': 'Datenschutzerklärung',
      'terms': 'Nutzungsbedingungen',
      'exportData': 'Meine Daten herunterladen',
      'exportSubtitle':
          'Lokaler JSON-Export von Profil, Analysen und Dokumenten',
      'deleteLocal': 'Lokales Archiv löschen',
      'deleteLocalSubtitle': 'Löscht nur Dokumente aus dem anonymen Archiv',
      'deleteLocalBody':
          'Dokumente, OCR-Text, Analysen und Erinnerungen werden dauerhaft vom Gerät gelöscht.',
      'deleteAccount': 'Konto dauerhaft löschen',
      'deleteAccountQuestion': 'Konto löschen?',
      'deleteAccountBody':
          'Dadurch werden lokale Dokumente, Analysen, Erinnerungen und das Konto dauerhaft gelöscht.',
      'prepareExport': 'Privater Datenexport wird vorbereitet…',
      'exportUnavailable': 'Datenexport ist derzeit nicht verfügbar.',
      'choosePlan': 'Tarif auswählen',
      'planTagline': 'Mehr Sicherheit, weniger Stress.',
      'freeFeature': 'Insgesamt 3 Testanalysen',
      'premiumFeature1': 'Analysen mit Schutz vor missbräuchlicher Nutzung',
      'premiumFeature2': 'KI-Antworten und Übersetzungen',
      'premiumFeature3': 'Archiv und Erinnerungen',
      'proFeature1': 'Für Familien und kleine Unternehmen',
      'proFeature2': 'Alles aus Premium mit höherem Nutzungslimit',
      'restorePurchases': 'Käufe wiederherstellen',
      'manageSubscription': 'Abo verwalten oder kündigen',
      'choosePlanButton': 'Tarif wählen',
      'newStatus': 'Neu',
      'progressStatus': 'In Bearbeitung',
      'doneStatus': 'Erledigt',
      'save': 'Speichern',
      'lastUpdated': 'Letzte Änderung: 26. Juli 2026.',
      'dataController': 'Verantwortlicher',
      'contact': 'Kontakt',
      'address': 'Adresse',
      'next': 'Weiter',
      'start': 'Sicher starten',
      'skip': 'Überspringen',
    },
    'en': {
      'home': 'Home',
      'archive': 'Archive',
      'assistant': 'Assistant',
      'profile': 'Profile',
      'welcome': 'Welcome',
      'homeSubtitle': 'Understand German letters in the language you prefer.',
      'analyzeNew': 'Analyze a new letter',
      'remaining': '{count} of 3 trial analyses remaining.',
      'unlimited': 'Premium analyses are active.',
      'addDocument': 'Add document',
      'activatePremium': 'Activate Premium',
      'recentLetters': 'Recent letters',
      'emptyLetters': 'No saved letters yet.',
      'accountCta': 'Sign in or create an account',
      'accountCtaSubtitle':
          'Your account protects your plan and separate local archive.',
      'appLanguage': 'App language',
      'signIn': 'Sign in',
      'createAccount': 'Create account',
      'secureLetters': 'Your account, plan and local archive remain separate.',
      'email': 'Email',
      'password': 'Password (at least 6 characters)',
      'continueGoogle': 'Continue with Google',
      'continueApple': 'Continue with Apple',
      'haveAccount': 'Already have an account? Sign in',
      'needAccount': 'No account? Register',
      'signInFailed': 'Sign-in failed',
      'myProfile': 'My profile',
      'preferredLanguage': 'Preferred language',
      'country': 'Country of origin',
      'addCountry': 'Add country of origin',
      'signInForProfile': 'Sign in to save your profile',
      'signOut': 'Sign out',
      'uploadDocument': 'Upload document',
      'localProcessing':
          'Images/PDFs and the archive stay local. With your consent, only OCR text is sent to OpenAI for the current analysis.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pdfImage': 'PDF or image',
      'letterText': 'Letter text',
      'ocrReading': 'Recognizing text locally…',
      'loadingImage': 'Loading photo…',
      'ocrReady': 'Document loaded and text recognized.',
      'ocrNotReady': 'Text has not been recognized yet.',
      'photoReadyForAnalysis': 'The photo is loaded. Tap “Analyse letter”.',
      'ocrFailed': 'Document was not recognized',
      'enterTextFirst': 'Photograph a document or enter the letter text.',
      'analyzeLetter': 'Analyze letter',
      'processing': 'AI is processing…',
      'newAnalysis': 'New analysis',
      'assistantTitle': 'AI assistant',
      'assistantHello':
          'Hello! Ask me about the most recently analyzed letter.',
      'assistantHint': 'For example: What is the deadline?',
      'onboardPhoto': 'Photograph a German letter',
      'onboardPhotoBody': 'Capture a document or upload a PDF or image.',
      'onboardAi': 'AI explains what it means',
      'onboardAiBody': 'A clear explanation in your language.',
      'onboardDeadline': 'Never miss a deadline',
      'onboardDeadlineBody': 'Receive reminders for important dates.',
      'analysisFailed': 'Analysis failed',
      'sessionExpired': 'Your session has expired. Please sign in again.',
      'tryAgain': 'Please try again.',
      'resultTitle': 'Analysis result',
      'simpleExplanation': 'Plain-language explanation',
      'category': 'Category',
      'deadline': 'Deadline',
      'amount': 'Amount found',
      'nextSteps': 'What to do next',
      'originalMissing':
          'The original document was not saved with this analysis.',
      'openOriginal': 'Open or download original',
      'generateReply': 'Generate reply',
      'finishHome': 'Finish and go home',
      'replyTitle': 'Suggested reply',
      'formalReply': 'Formal German reply',
      'letter': 'Letter',
      'responseUnavailable': 'Reply unavailable',
      'replyCopied': 'Reply copied.',
      'copyReply': 'Copy reply',
      'sendEmail': 'Send email',
      'savePdf': 'Save PDF',
      'archiveSubtitle': 'Your letters are organized by status and category.',
      'deleteDocument': 'Delete document',
      'deleteDocumentBody':
          'The original, OCR text and analysis will be permanently deleted from this device only.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'name': 'Name',
      'addName': 'Add name',
      'premiumActive': 'Premium is active',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analyses, replies and reminders with responsible use',
      'freeBetaActive': 'Free beta: OpenAI analysis with safety limits.',
      'freeBetaTitle': 'BriefAI free beta',
      'freeBetaBody':
          'Payments are disabled while we test quality. Originals remain local; with consent, only OCR text is sent for the current OpenAI request.',
      'privacyPolicy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'exportData': 'Download my data',
      'exportSubtitle': 'Local JSON export of profile, analyses and documents',
      'deleteLocal': 'Delete local archive',
      'deleteLocalSubtitle':
          'Deletes documents from the anonymous archive only',
      'deleteLocalBody':
          'Documents, OCR text, analyses and reminders will be permanently deleted from this device.',
      'deleteAccount': 'Permanently delete account',
      'deleteAccountQuestion': 'Delete account?',
      'deleteAccountBody':
          'This permanently deletes local documents, analyses, reminders and the user account.',
      'prepareExport': 'Preparing private data export…',
      'exportUnavailable': 'Data export is currently unavailable.',
      'choosePlan': 'Choose a plan',
      'planTagline': 'More confidence, less stress.',
      'freeFeature': '3 trial analyses in total',
      'premiumFeature1': 'Analyses with responsible-use protection',
      'premiumFeature2': 'AI replies and translations',
      'premiumFeature3': 'Archive and reminders',
      'proFeature1': 'For families and small businesses',
      'proFeature2': 'Everything in Premium with a higher usage threshold',
      'restorePurchases': 'Restore purchases',
      'manageSubscription': 'Manage or cancel subscription',
      'choosePlanButton': 'Choose plan',
      'newStatus': 'New',
      'progressStatus': 'In progress',
      'doneStatus': 'Done',
      'save': 'Save',
      'lastUpdated': 'Last updated: July 26, 2026.',
      'dataController': 'Data controller',
      'contact': 'Contact',
      'address': 'Address',
      'next': 'Continue',
      'start': 'Start securely',
      'skip': 'Skip',
    },
    'bg': {
      'home': 'Начало',
      'archive': 'Архив',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добре дошли',
      'homeSubtitle': 'Разбирайте немските писма на предпочитания от вас език.',
      'analyzeNew': 'Анализирай ново писмо',
      'remaining': 'Остават {count} от 3 пробни анализа.',
      'unlimited': 'Premium анализите са активни.',
      'addDocument': 'Добави документ',
      'activatePremium': 'Активирай Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Все още няма запазени писма.',
      'accountCta': 'Влезте или създайте акаунт',
      'accountCtaSubtitle': 'Акаунтът пази плана и отделния локален архив.',
      'appLanguage': 'Език на приложението',
      'signIn': 'Вход',
      'createAccount': 'Създай акаунт',
      'secureLetters': 'Акаунтът, планът и локалният архив остават отделни.',
      'email': 'Имейл',
      'password': 'Парола (поне 6 знака)',
      'continueGoogle': 'Продължи с Google',
      'continueApple': 'Продължи с Apple',
      'haveAccount': 'Имате акаунт? Влезте',
      'needAccount': 'Нямате акаунт? Регистрирайте се',
      'signInFailed': 'Входът е неуспешен',
      'myProfile': 'Моят профил',
      'preferredLanguage': 'Предпочитан език',
      'country': 'Държава на произход',
      'addCountry': 'Добавете държава на произход',
      'signInForProfile': 'Влезте, за да запазите профила',
      'signOut': 'Изход',
      'uploadDocument': 'Качете документ',
      'localProcessing':
          'Изображението/PDF и архивът остават локално. С ваше съгласие само OCR текстът се изпраща до OpenAI за текущия анализ.',
      'camera': 'Камера',
      'gallery': 'Галерия',
      'pdfImage': 'PDF или изображение',
      'letterText': 'Текст на писмото',
      'ocrReading': 'Разпознавам текста локално…',
      'loadingImage': 'Зареждам снимката…',
      'ocrReady': 'Документът е зареден и текстът е разпознат.',
      'ocrNotReady': 'Текстът все още не е разпознат.',
      'photoReadyForAnalysis':
          'Снимката е заредена. Натиснете „Анализирай писмото“.',
      'ocrFailed': 'Документът не е разпознат',
      'enterTextFirst': 'Снимайте документ или въведете текста.',
      'analyzeLetter': 'Анализирай писмо',
      'processing': 'AI обработва…',
      'newAnalysis': 'Нов анализ',
      'assistantTitle': 'AI асистент',
      'assistantHello':
          'Здравейте! Попитайте ме за последното анализирано писмо.',
      'assistantHint': 'Напр. Какъв е срокът?',
      'onboardPhoto': 'Снимайте немско писмо',
      'onboardPhotoBody': 'Снимайте документ или качете PDF/изображение.',
      'onboardAi': 'AI обяснява значението',
      'onboardAiBody': 'Ясно обяснение на вашия език.',
      'onboardDeadline': 'Не пропускайте срокове',
      'onboardDeadlineBody': 'Получавайте напомняния за важни дати.',
      'analysisFailed': 'Анализът е неуспешен',
      'sessionExpired': 'Сесията изтече. Влезте отново.',
      'tryAgain': 'Опитайте отново.',
      'resultTitle': 'Резултат от анализа',
      'simpleExplanation': 'Обяснение на разбираем език',
      'category': 'Категория',
      'deadline': 'Срок',
      'amount': 'Открита сума',
      'nextSteps': 'Какво да направите сега',
      'originalMissing': 'Оригиналният документ не е запазен с анализа.',
      'openOriginal': 'Отвори или изтегли оригинала',
      'generateReply': 'Генерирай отговор',
      'finishHome': 'Завърши и към началото',
      'replyTitle': 'Предложен отговор',
      'formalReply': 'Официален отговор на немски',
      'letter': 'Писмо',
      'responseUnavailable': 'Отговорът не е достъпен',
      'replyCopied': 'Отговорът е копиран.',
      'copyReply': 'Копирай отговор',
      'sendEmail': 'Изпрати имейл',
      'savePdf': 'Запази PDF',
      'archiveSubtitle': 'Писмата са организирани по статус и категория.',
      'deleteDocument': 'Изтрий документ',
      'deleteDocumentBody':
          'Оригиналът, OCR текстът и анализът ще бъдат изтрити само от това устройство.',
      'cancel': 'Отказ',
      'delete': 'Изтрий',
      'name': 'Име',
      'addName': 'Добавете име',
      'premiumActive': 'Premium е активен',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Анализи, отговори и напомняния с отговорна употреба',
      'freeBetaActive': 'Безплатна бета: OpenAI анализ със защитни лимити.',
      'freeBetaTitle': 'Безплатна бета на BriefAI',
      'freeBetaBody':
          'Плащанията са изключени, докато тестваме качеството. Оригиналите остават локално; със съгласие се изпраща само OCR текстът.',
      'privacyPolicy': 'Политика за поверителност',
      'terms': 'Условия за ползване',
      'exportData': 'Изтегли моите данни',
      'exportSubtitle': 'Локален JSON експорт на профил, анализи и документи',
      'deleteLocal': 'Изтрий локалния архив',
      'deleteLocalSubtitle': 'Изтрива само анонимния архив',
      'deleteLocalBody':
          'Документите, OCR текстът, анализите и напомнянията ще бъдат изтрити от устройството.',
      'deleteAccount': 'Изтрий акаунта завинаги',
      'deleteAccountQuestion': 'Да се изтрие ли акаунтът?',
      'deleteAccountBody':
          'Това изтрива завинаги локалните документи, анализи, напомняния и акаунта.',
      'prepareExport': 'Подготвям частен експорт…',
      'exportUnavailable': 'Експортът в момента не е достъпен.',
      'choosePlan': 'Изберете план',
      'planTagline': 'Повече сигурност, по-малко стрес.',
      'freeFeature': 'Общо 3 пробни анализа',
      'premiumFeature1': 'Анализи със защита за отговорна употреба',
      'premiumFeature2': 'AI отговори и преводи',
      'premiumFeature3': 'Архив и напомняния',
      'proFeature1': 'За семейства и малки фирми',
      'proFeature2': 'Всичко от Premium с по-висок праг',
      'restorePurchases': 'Възстанови покупки',
      'manageSubscription': 'Управлявай или откажи абонамента',
      'choosePlanButton': 'Избери план',
      'newStatus': 'Ново',
      'progressStatus': 'В процес',
      'doneStatus': 'Завършено',
      'save': 'Запази',
      'lastUpdated': 'Последна промяна: 26 юли 2026 г.',
      'dataController': 'Администратор на данни',
      'contact': 'Контакт',
      'address': 'Адрес',
      'next': 'Продължи',
      'start': 'Започни сигурно',
      'skip': 'Пропусни',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) async => AppStrings(locale);

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
