import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  /// Languages users can choose for AI explanations and replies.
  ///
  /// The eight fully translated interfaces keep their native copy. For every
  /// additional language the interface uses English until its complete static
  /// translation ships, while OpenAI receives the selected BCP-47 code and
  /// answers in that language immediately.
  static const languageLabels = <String, String>{
    'sq': 'Shqip',
    'ar': 'العربية',
    'hy': 'Հայերեն',
    'az': 'Azərbaycanca',
    'bn': 'বাংলা',
    'bs': 'Bosanski',
    'bg': 'Български',
    'zh': '中文',
    'hr': 'Hrvatski',
    'cs': 'Čeština',
    'da': 'Dansk',
    'nl': 'Nederlands',
    'en': 'English',
    'et': 'Eesti',
    'fa': 'فارسی',
    'fi': 'Suomi',
    'fr': 'Français',
    'ka': 'ქართული',
    'de': 'Deutsch',
    'el': 'Ελληνικά',
    'he': 'עברית',
    'hi': 'हिन्दी',
    'hu': 'Magyar',
    'is': 'Íslenska',
    'id': 'Bahasa Indonesia',
    'it': 'Italiano',
    'ja': '日本語',
    'kk': 'Қазақша',
    'ko': '한국어',
    'lv': 'Latviešu',
    'lt': 'Lietuvių',
    'mk': 'Македонски',
    'ms': 'Bahasa Melayu',
    'no': 'Norsk',
    'ps': 'پښتو',
    'pl': 'Polski',
    'pt': 'Português',
    'ro': 'Română',
    'ru': 'Русский',
    'sr': 'Srpski',
    'sk': 'Slovenčina',
    'sl': 'Slovenščina',
    'es': 'Español',
    'sw': 'Kiswahili',
    'sv': 'Svenska',
    'ta': 'தமிழ்',
    'th': 'ไทย',
    'tr': 'Türkçe',
    'uk': 'Українська',
    'ur': 'اردو',
    'uz': 'O‘zbekcha',
    'vi': 'Tiếng Việt',
  };

  static final supportedLocales = languageLabels.keys
      .map(Locale.new)
      .toList(growable: false);

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings) ??
      const AppStrings(Locale('sr'));

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  String remaining(int value) =>
      text('remaining').replaceFirst('{count}', value.toString());

  String pagesSelected(int value) =>
      text('pagesSelected').replaceFirst('{count}', value.toString());

  String ocrProgress(int current, int total) => text('ocrProgress')
      .replaceFirst('{current}', current.toString())
      .replaceFirst('{total}', total.toString());

  String maxPages(int value) =>
      text('maxPages').replaceFirst('{count}', value.toString());

  String category(String key) =>
      (_categories[locale.languageCode] ?? _categories['en']!)[key] ??
      _categories['en']![key] ??
      key;

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  static const _categories = <String, Map<String, String>>{
    'sr': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Stanodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanska služba',
      'sozialamt': 'Socijalna služba',
      'jugendamt': 'Služba za mlade i porodicu',
      'wohngeldstelle': 'Služba za Wohngeld',
      'bafoegAmt': 'BAföG služba',
      'rentenversicherung': 'Penzijsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Snabdevač energijom',
      'debtCollection': 'Inkaso',
      'police': 'Policija / tužilaštvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'hr': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Najmodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanski ured',
      'sozialamt': 'Socijalni ured',
      'jugendamt': 'Ured za mlade i obitelj',
      'wohngeldstelle': 'Ured za Wohngeld',
      'bafoegAmt': 'BAföG ured',
      'rentenversicherung': 'Mirovinsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Opskrbljivač energijom',
      'debtCollection': 'Naplata potraživanja',
      'police': 'Policija / tužiteljstvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'bs': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Zdravstveno osiguranje',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Osiguranje',
      'telecom': 'Telekom',
      'employer': 'Poslodavac',
      'landlord': 'Stanodavac',
      'school': 'Škola',
      'kindergarten': 'Vrtić',
      'court': 'Sud',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agencija za zapošljavanje',
      'auslaenderbehoerde': 'Služba za strance',
      'buergeramt': 'Građanska služba',
      'sozialamt': 'Socijalna služba',
      'jugendamt': 'Služba za mlade i porodicu',
      'wohngeldstelle': 'Služba za Wohngeld',
      'bafoegAmt': 'BAföG služba',
      'rentenversicherung': 'Penzijsko osiguranje',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Snabdjevač energijom',
      'debtCollection': 'Inkaso',
      'police': 'Policija / tužilaštvo',
      'customs': 'Carina (Zoll)',
      'other': 'Ostalo',
    },
    'mk': {
      'finanzamt': 'Даночна управа',
      'krankenkasse': 'Здравствено осигурување',
      'jobcenter': 'Jobcenter',
      'bank': 'Банка',
      'insurance': 'Осигурување',
      'telecom': 'Телеком',
      'employer': 'Работодавач',
      'landlord': 'Сопственик на стан',
      'school': 'Училиште',
      'kindergarten': 'Градинка',
      'court': 'Суд',
      'familienkasse': 'Familienkasse / детски додаток',
      'agenturFuerArbeit': 'Агенција за вработување',
      'auslaenderbehoerde': 'Служба за странци',
      'buergeramt': 'Граѓанска служба',
      'sozialamt': 'Социјална служба',
      'jugendamt': 'Служба за млади и семејство',
      'wohngeldstelle': 'Служба за Wohngeld',
      'bafoegAmt': 'BAföG служба',
      'rentenversicherung': 'Пензиско осигурување',
      'rundfunkbeitrag': 'Радиодифузна такса',
      'energy': 'Снабдувач со енергија',
      'debtCollection': 'Наплата на долг',
      'police': 'Полиција / обвинителство',
      'customs': 'Царина (Zoll)',
      'other': 'Друго',
    },
    'de': {
      'finanzamt': 'Finanzamt',
      'krankenkasse': 'Krankenkasse',
      'jobcenter': 'Jobcenter',
      'bank': 'Bank',
      'insurance': 'Versicherung',
      'telecom': 'Telekommunikation',
      'employer': 'Arbeitgeber',
      'landlord': 'Vermieter',
      'school': 'Schule',
      'kindergarten': 'Kindergarten',
      'court': 'Gericht',
      'familienkasse': 'Familienkasse / Kindergeld',
      'agenturFuerArbeit': 'Agentur für Arbeit',
      'auslaenderbehoerde': 'Ausländerbehörde',
      'buergeramt': 'Bürgeramt',
      'sozialamt': 'Sozialamt',
      'jugendamt': 'Jugendamt',
      'wohngeldstelle': 'Wohngeldstelle',
      'bafoegAmt': 'BAföG-Amt',
      'rentenversicherung': 'Rentenversicherung',
      'rundfunkbeitrag': 'Rundfunkbeitrag',
      'energy': 'Energieversorger',
      'debtCollection': 'Inkasso',
      'police': 'Polizei / Staatsanwaltschaft',
      'customs': 'Zoll',
      'other': 'Sonstiges',
    },
    'en': {
      'finanzamt': 'Tax office',
      'krankenkasse': 'Health insurer',
      'jobcenter': 'Jobcenter',
      'bank': 'Bank',
      'insurance': 'Insurance',
      'telecom': 'Telecom',
      'employer': 'Employer',
      'landlord': 'Landlord',
      'school': 'School',
      'kindergarten': 'Kindergarten',
      'court': 'Court',
      'familienkasse': 'Familienkasse / child benefit',
      'agenturFuerArbeit': 'Employment Agency',
      'auslaenderbehoerde': 'Immigration authority',
      'buergeramt': 'Citizens’ office',
      'sozialamt': 'Social welfare office',
      'jugendamt': 'Youth welfare office',
      'wohngeldstelle': 'Housing benefit office',
      'bafoegAmt': 'BAföG office',
      'rentenversicherung': 'Pension insurance',
      'rundfunkbeitrag': 'Broadcasting contribution',
      'energy': 'Energy supplier',
      'debtCollection': 'Debt collection',
      'police': 'Police / prosecution office',
      'customs': 'Customs (Zoll)',
      'other': 'Other',
    },
    'tr': {
      'finanzamt': 'Vergi dairesi',
      'krankenkasse': 'Sağlık sigortası',
      'jobcenter': 'Jobcenter',
      'bank': 'Banka',
      'insurance': 'Sigorta',
      'telecom': 'Telekomünikasyon',
      'employer': 'İşveren',
      'landlord': 'Ev sahibi',
      'school': 'Okul',
      'kindergarten': 'Anaokulu',
      'court': 'Mahkeme',
      'familienkasse': 'Familienkasse / çocuk parası',
      'agenturFuerArbeit': 'İş Ajansı',
      'auslaenderbehoerde': 'Yabancılar dairesi',
      'buergeramt': 'Vatandaşlık işleri dairesi',
      'sozialamt': 'Sosyal yardım dairesi',
      'jugendamt': 'Gençlik dairesi',
      'wohngeldstelle': 'Konut yardımı dairesi',
      'bafoegAmt': 'BAföG dairesi',
      'rentenversicherung': 'Emeklilik sigortası',
      'rundfunkbeitrag': 'Radyo-televizyon katkı payı',
      'energy': 'Enerji sağlayıcısı',
      'debtCollection': 'Borç tahsilatı',
      'police': 'Polis / savcılık',
      'customs': 'Gümrük (Zoll)',
      'other': 'Diğer',
    },
    '_trUi': {
      'home': 'Ana sayfa',
      'archive': 'Arşiv',
      'assistant': 'Asistan',
      'profile': 'Profil',
      'welcome': 'Hoş geldiniz',
      'homeSubtitle': 'Almanca mektupları tercih ettiğiniz dilde anlayın.',
      'analyzeNew': 'Yeni bir mektubu analiz et',
      'remaining': '{count} ücretsiz başlangıç analizi kaldı.',
      'unlimited': 'Premium analizler etkin.',
      'monthlyPlanActive': 'Aylık analiz paketiniz etkin.',
      'addDocument': 'Belge ekle',
      'activatePremium': 'Premium’u etkinleştir',
      'recentLetters': 'Son mektuplar',
      'emptyLetters': 'Henüz kaydedilmiş mektup yok.',
      'accountCta': 'Giriş yapın veya hesap oluşturun',
      'accountCtaSubtitle':
          'Hesabınız planınızı korur; arşiv bu cihazda yerel kalır.',
      'appLanguage': 'Uygulama dili',
      'signIn': 'Giriş yap',
      'createAccount': 'Hesap oluştur',
      'secureLetters':
          'Hesabınız ve planınız korunur; mektuplar cihazda yerel kalır.',
      'email': 'E-posta',
      'password': 'Şifre (en az 6 karakter)',
      'continueGoogle': 'Google ile devam et',
      'continueApple': 'Apple ile devam et',
      'haveAccount': 'Zaten hesabınız var mı? Giriş yapın',
      'needAccount': 'Hesabınız yok mu? Kaydolun',
      'signInFailed': 'Giriş başarısız oldu',
      'myProfile': 'Profilim',
      'preferredLanguage': 'Tercih edilen dil',
      'country': 'Menşe ülke',
      'addCountry': 'Menşe ülke ekle',
      'signInForProfile': 'Profili kaydetmek için giriş yapın',
      'signOut': 'Çıkış yap',
      'uploadDocument': 'Belge yükle',
      'localProcessing':
          'Resimler/PDF’ler ve arşiv yerel kalır. Onayınızla yalnızca OCR metni mevcut analiz için OpenAI’ye gönderilir.',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'pdfImage': 'PDF veya resim',
      'page': 'Sayfa',
      'pagesSelected': '{count} sayfa seçildi',
      'ocrProgress': '{total} sayfanın {current}. sayfası tanınıyor…',
      'removePage': 'Sayfayı kaldır',
      'maxPages': 'Bir mektuba en fazla {count} sayfa ekleyebilirsiniz.',
      'filesTooLarge': 'Seçilen sayfalar cihaz için fazla büyük.',
      'letterText': 'Mektup metni',
      'ocrReading': 'Metin cihazda tanınıyor…',
      'loadingImage': 'Fotoğraf yükleniyor…',
      'ocrReady': 'Belge yüklendi ve metin tanındı.',
      'ocrNotReady': 'Metin henüz tanınmadı.',
      'photoReadyForAnalysis':
          'Fotoğraf yüklendi. “Mektubu analiz et” düğmesine dokunun.',
      'ocrFailed': 'Belge tanınamadı',
      'enterTextFirst': 'Bir belgeyi fotoğraflayın veya mektup metnini girin.',
      'analyzeLetter': 'Mektubu analiz et',
      'processing': 'Yapay zekâ işliyor…',
      'newAnalysis': 'Yeni analiz',
      'assistantTitle': 'Yapay zekâ asistanı',
      'assistantHello':
          'Merhaba! Son analiz edilen mektup hakkında bana soru sorun.',
      'assistantHint': 'Örneğin: Son tarih nedir?',
      'onboardPhoto': 'Almanca bir mektubu fotoğraflayın',
      'onboardPhotoBody': 'Belgeyi çekin veya PDF ya da resim yükleyin.',
      'onboardAi': 'Yapay zekâ anlamını açıklar',
      'onboardAiBody': 'Kendi dilinizde açık bir açıklama.',
      'onboardDeadline': 'Hiçbir son tarihi kaçırmayın',
      'onboardDeadlineBody': 'Önemli tarihler için hatırlatıcı alın.',
      'analysisFailed': 'Analiz başarısız oldu',
      'sessionExpired': 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.',
      'tryAgain': 'Lütfen tekrar deneyin.',
      'resultTitle': 'Analiz sonucu',
      'simpleExplanation': 'Basit dille açıklama',
      'senderName': 'Gönderen / faturayı düzenleyen',
      'recipientName': 'Mektup veya fatura alıcısı',
      'paymentRecipient': 'Ödeme alıcısı',
      'documentType': 'Belge türü',
      'invoiceNumber': 'Fatura numarası',
      'servicePeriod': 'Hizmet veya fatura dönemi',
      'paymentReference': 'Ödeme açıklaması',
      'category': 'Kategori',
      'deadline': 'Son tarih',
      'amount': 'Bulunan tutar',
      'paymentObligation': 'Ödeme yükümlülüğü',
      'paymentDueDate': 'Ödeme son tarihi',
      'paymentOpen': 'Ödeme bekliyor',
      'paymentPaid': 'Ödendi',
      'nextSteps': 'Bundan sonra ne yapmalısınız',
      'originalMissing': 'Orijinal belge bu analizle birlikte kaydedilmemiş.',
      'openOriginal': 'Orijinali aç veya indir',
      'generateReply': 'Yanıt oluştur',
      'replyFactsTitle': 'Kendi açıklamanızı ekleyin',
      'replyFactsHelp':
          'Olanları kendi dilinizde yazın. Yapay zekâ bu bilgileri mektubun tüm sayfalarıyla birleştirip profesyonel bir Almanca yanıt oluşturur. Bilmediğiniz hiçbir şeyi eklemeyin.',
      'replyFactsHint':
          'Örn. Neden itiraz ettiğinizi, daha önce ne olduğunu ve karşı taraftan ne istediğinizi yazın…',
      'finishHome': 'Bitir ve ana sayfaya dön',
      'replyTitle': 'Önerilen yanıt',
      'formalReply': 'Resmî Almanca yanıt',
      'letter': 'Mektup',
      'responseUnavailable': 'Yanıt kullanılamıyor',
      'replyCopied': 'Yanıt kopyalandı.',
      'copyReply': 'Yanıtı kopyala',
      'sendEmail': 'E-posta gönder',
      'emailOpenFailed': 'E-posta uygulaması açılamadı',
      'savePdf': 'PDF olarak kaydet',
      'replySavedLocally': 'Yanıt bu hesap için cihazda kaydedildi.',
      'editReplyContext': 'Açıklamayı düzenle ve yeniden oluştur',
      'pdfReady': 'PDF paylaşmaya veya kaydetmeye hazır.',
      'pdfSaveFailed': 'PDF kaydedilemedi',
      'archiveSubtitle': 'Mektuplarınız durum ve kategoriye göre düzenlenir.',
      'deleteDocument': 'Belgeyi sil',
      'deleteDocumentBody':
          'Orijinal, OCR metni ve analiz yalnızca bu cihazdan kalıcı olarak silinir.',
      'cancel': 'İptal',
      'delete': 'Sil',
      'name': 'Ad',
      'addName': 'Ad ekle',
      'premiumActive': 'Premium etkin',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle':
          'Sorumlu kullanım sınırlarıyla analizler, yanıtlar ve hatırlatıcılar',
      'privacyPolicy': 'Gizlilik Politikası',
      'terms': 'Şartlar ve Koşullar',
      'exportData': 'Verilerimi indir',
      'exportSubtitle':
          'Profil, analizler ve belgelerin yerel JSON dışa aktarımı',
      'deleteLocal': 'Yerel arşivi sil',
      'deleteLocalSubtitle':
          'Bu cihazdaki tüm yerel belgeleri ve analizleri siler',
      'deleteLocalBody':
          'Belgeler, OCR metni, analizler ve hatırlatıcılar bu cihazdan kalıcı olarak silinir.',
      'deleteAccount': 'Hesabı kalıcı olarak sil',
      'deleteAccountQuestion': 'Hesap silinsin mi?',
      'deleteAccountBody':
          'Bu işlem yerel belgeleri, analizleri, hatırlatıcıları ve kullanıcı hesabını kalıcı olarak siler.',
      'prepareExport': 'Özel veri dışa aktarımı hazırlanıyor…',
      'exportUnavailable': 'Veri dışa aktarımı şu anda kullanılamıyor.',
      'choosePlan': 'Bir plan seçin',
      'planTagline': 'Daha fazla güven, daha az stres.',
      'freeFeature': 'Yeni hesaplar için 5 başlangıç analizi',
      'premiumFeature1': 'Sorumlu kullanım korumalı analizler',
      'analysesPerMonth': 'Ayda {count} mektup analizi',
      'premiumFeature2': 'Yapay zekâ yanıtları ve çeviriler',
      'premiumFeature3': 'Arşiv ve hatırlatıcılar',
      'proFeature1': 'Aileler ve küçük işletmeler için',
      'proFeature2': 'Daha yüksek kullanım sınırıyla tüm Premium özellikler',
      'restorePurchases': 'Satın alımları geri yükle',
      'manageSubscription': 'Aboneliği yönet veya iptal et',
      'choosePlanButton': 'Planı seç',
      'newStatus': 'Yeni',
      'progressStatus': 'İşlemde',
      'doneStatus': 'Tamamlandı',
      'save': 'Kaydet',
      'lastUpdated': 'Son güncelleme: 27 Temmuz 2026.',
      'dataController': 'Veri sorumlusu',
      'contact': 'İletişim',
      'address': 'Adres',
      'next': 'Devam',
      'start': 'Güvenle başla',
      'skip': 'Atla',
    },
    'bg': {
      'finanzamt': 'Данъчна служба',
      'krankenkasse': 'Здравно осигуряване',
      'jobcenter': 'Jobcenter',
      'bank': 'Банка',
      'insurance': 'Застраховане',
      'telecom': 'Телеком',
      'employer': 'Работодател',
      'landlord': 'Наемодател',
      'school': 'Училище',
      'kindergarten': 'Детска градина',
      'court': 'Съд',
      'familienkasse': 'Familienkasse / детски надбавки',
      'agenturFuerArbeit': 'Агенция по заетостта',
      'auslaenderbehoerde': 'Служба за чужденци',
      'buergeramt': 'Гражданска служба',
      'sozialamt': 'Социална служба',
      'jugendamt': 'Служба за младежи и семейство',
      'wohngeldstelle': 'Служба за Wohngeld',
      'bafoegAmt': 'BAföG служба',
      'rentenversicherung': 'Пенсионно осигуряване',
      'rundfunkbeitrag': 'Такса за обществено излъчване',
      'energy': 'Доставчик на енергия',
      'debtCollection': 'Събиране на вземания',
      'police': 'Полиция / прокуратура',
      'customs': 'Митници (Zoll)',
      'other': 'Друго',
    },
  };

  static final _values = <String, Map<String, String>>{
    'tr': _categories['_trUi']!,
    'sr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumite nemačka pisma, na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo uvodnih analiza: {count}.',
      'unlimited': 'Premium analize su aktivne.',
      'monthlyPlanActive': 'Aktivan je vaš mesečni paket analiza.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Poslednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili kreirajte nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Kreiraj nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi sa Google',
      'continueApple': 'Nastavi sa Apple',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Preferirani jezik',
      'country': 'Zemlja porekla',
      'addCountry': 'Dodajte zemlju porekla',
      'signInForProfile': 'Prijavite se da biste sačuvali profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu saglasnost samo OCR tekst se šalje OpenAI-ju za trenutnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'page': 'Strana',
      'pagesSelected': 'Izabrano strana: {count}',
      'ocrProgress': 'Prepoznajem stranu {current} od {total}…',
      'removePage': 'Ukloni stranu',
      'maxPages': 'Jedno pismo može imati najviše {count} strana.',
      'filesTooLarge': 'Izabrane strane su prevelike za ovaj uređaj.',
      'letterText': 'Tekst sa pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografišite dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o poslednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografiši nemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propusti rokove',
      'onboardDeadlineBody': 'Dobijte podsetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovo.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'senderName': 'Pošiljalac / izdavalac',
      'recipientName': 'Primalac pisma ili računa',
      'paymentRecipient': 'Primalac uplate',
      'documentType': 'Vrsta dokumenta',
      'invoiceNumber': 'Broj računa',
      'servicePeriod': 'Period usluge ili obračuna',
      'paymentReference': 'Poziv na broj / svrha uplate',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađen iznos',
      'paymentObligation': 'Obaveza plaćanja',
      'paymentDueDate': 'Rok za plaćanje',
      'paymentOpen': 'Plaćanje je otvoreno',
      'paymentPaid': 'Plaćeno',
      'nextSteps': 'Šta sada da uradite',
      'originalMissing': 'Originalni dokument nije sačuvan uz analizu.',
      'openOriginal': 'Otvori ili preuzmi original',
      'generateReply': 'Generiši odgovor',
      'replyFactsTitle': 'Dodajte svoje objašnjenje',
      'replyFactsHelp':
          'Napišite svojim jezikom šta se dogodilo. AI će to spojiti sa svim stranama pisma i sastaviti profesionalan odgovor na nemačkom. Unesite samo proverene činjenice.',
      'replyFactsHint':
          'Npr. objasnite zašto osporavate zahtev, šta se ranije dogodilo i šta tražite od pošiljaoca…',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Predlog odgovora',
      'formalReply': 'Formalni nemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-mail',
      'emailOpenFailed': 'Aplikacija za e-mail nije otvorena',
      'savePdf': 'Sačuvaj PDF',
      'replySavedLocally': 'Odgovor je sačuvan na uređaju za ovaj nalog.',
      'editReplyContext': 'Izmeni objašnjenje i generiši ponovo',
      'pdfReady': 'PDF je spreman za čuvanje ili deljenje.',
      'pdfSaveFailed': 'PDF nije sačuvan',
      'archiveSubtitle': 'Vaša pisma su organizovana po statusu i kategoriji.',
      'deleteDocument': 'Obriši dokument',
      'deleteDocumentBody':
          'Original, OCR tekst i analiza biće trajno obrisani samo sa ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Obriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analize, odgovori i podsetnici uz odgovornu upotrebu',
      'privacyPolicy': 'Politika privatnosti',
      'terms': 'Uslovi korišćenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle':
          'Lokalni JSON izvoz profila, analiza i originalnih dokumenata',
      'deleteLocal': 'Obriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše dokumente samo iz anonimne arhive',
      'deleteLocalBody':
          'Originalni dokumenti, OCR tekst, analize i podsetnici biće trajno obrisani sa ovog uređaja.',
      'deleteAccount': 'Trajno obriši nalog',
      'deleteAccountQuestion': 'Obrisati nalog?',
      'deleteAccountBody':
          'Ova radnja trajno briše lokalne dokumente, analize, podsetnike i korisnički nalog.',
      'prepareExport': 'Pripremam privatni izvoz podataka…',
      'exportUnavailable': 'Izvoz podataka trenutno nije dostupan.',
      'choosePlan': 'Izaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '5 uvodnih analiza za novi nalog',
      'premiumFeature1': 'Analize uz zaštitu odgovorne upotrebe',
      'analysesPerMonth': '{count} analiza pisama mesečno',
      'premiumFeature2': 'AI odgovori i prevodi',
      'premiumFeature3': 'Arhiva i podsetnici',
      'proFeature1': 'Za porodice i male firme',
      'proFeature2': 'Sve iz Premium paketa i viši prag upotrebe',
      'restorePurchases': 'Vrati kupovine',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Izaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'Rešavam',
      'doneStatus': 'Završeno',
      'save': 'Sačuvaj',
      'lastUpdated': 'Poslednja izmena: 26. jul 2026.',
      'dataController': 'Vlasnik podataka',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni bezbedno',
      'skip': 'Preskoči',
    },
    'hr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo uvodnih analiza: {count}.',
      'unlimited': 'Premium analize su aktivne.',
      'monthlyPlanActive': 'Aktivan je vaš mjesečni paket analiza.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate spremljenih pisama.',
      'accountCta': 'Prijavite se ili izradite račun',
      'accountCtaSubtitle': 'Račun štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Izradi račun',
      'secureLetters': 'Vaš račun, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'E-pošta',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate račun? Prijavite se',
      'needAccount': 'Nemate račun? Registrirajte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja podrijetla',
      'addCountry': 'Dodajte zemlju podrijetla',
      'signInForProfile': 'Prijavite se za spremanje profila',
      'signOut': 'Odjava',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu privolu samo OCR tekst šalje se OpenAI-ju za trenutačnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'page': 'Stranica',
      'pagesSelected': 'Odabrano stranica: {count}',
      'ocrProgress': 'Prepoznajem stranicu {current} od {total}…',
      'removePage': 'Ukloni stranicu',
      'maxPages': 'Jedno pismo može imati najviše {count} stranica.',
      'filesTooLarge': 'Odabrane stranice prevelike su za ovaj uređaj.',
      'letterText': 'Tekst pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografirajte dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Pozdrav! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografirajte njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava značenje',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Primajte podsjetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspjela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovno.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'senderName': 'Pošiljatelj / izdavatelj',
      'recipientName': 'Primatelj pisma ili računa',
      'paymentRecipient': 'Primatelj uplate',
      'documentType': 'Vrsta dokumenta',
      'invoiceNumber': 'Broj računa',
      'servicePeriod': 'Razdoblje usluge ili obračuna',
      'paymentReference': 'Poziv na broj / svrha uplate',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađeni iznos',
      'paymentObligation': 'Obveza plaćanja',
      'paymentDueDate': 'Rok za plaćanje',
      'paymentOpen': 'Plaćanje je otvoreno',
      'paymentPaid': 'Plaćeno',
      'nextSteps': 'Što sada trebate učiniti',
      'originalMissing': 'Izvorni dokument nije spremljen uz analizu.',
      'openOriginal': 'Otvori ili preuzmi izvornik',
      'generateReply': 'Generiraj odgovor',
      'replyFactsTitle': 'Dodajte svoje objašnjenje',
      'replyFactsHelp':
          'Napišite svojim jezikom što se dogodilo. AI će to spojiti sa svim stranicama pisma i sastaviti profesionalan odgovor na njemačkom. Unesite samo provjerene činjenice.',
      'replyFactsHint':
          'Npr. objasnite zašto osporavate zahtjev, što se ranije dogodilo i što tražite od pošiljatelja…',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Prijedlog odgovora',
      'formalReply': 'Formalni njemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-poštu',
      'emailOpenFailed': 'Aplikacija za e-poštu nije otvorena',
      'savePdf': 'Spremi PDF',
      'replySavedLocally': 'Odgovor je spremljen na uređaju za ovaj račun.',
      'editReplyContext': 'Uredi objašnjenje i generiraj ponovno',
      'pdfReady': 'PDF je spreman za spremanje ili dijeljenje.',
      'pdfSaveFailed': 'PDF nije spremljen',
      'archiveSubtitle': 'Vaša su pisma organizirana po statusu i kategoriji.',
      'deleteDocument': 'Izbriši dokument',
      'deleteDocumentBody':
          'Izvornik, OCR tekst i analiza trajno će se izbrisati samo s ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Izbriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analize, odgovori i podsjetnici uz odgovornu uporabu',
      'privacyPolicy': 'Pravila privatnosti',
      'terms': 'Uvjeti korištenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle': 'Lokalni JSON izvoz profila, analiza i dokumenata',
      'deleteLocal': 'Izbriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše samo anonimnu arhivu',
      'deleteLocalBody':
          'Dokumenti, OCR tekst, analize i podsjetnici trajno će se izbrisati s uređaja.',
      'deleteAccount': 'Trajno izbriši račun',
      'deleteAccountQuestion': 'Izbrisati račun?',
      'deleteAccountBody':
          'Time se trajno brišu lokalni dokumenti, analize, podsjetnici i račun.',
      'prepareExport': 'Pripremam privatni izvoz…',
      'exportUnavailable': 'Izvoz trenutačno nije dostupan.',
      'choosePlan': 'Odaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '5 uvodnih analiza za novi račun',
      'premiumFeature1': 'Analize uz zaštitu odgovorne uporabe',
      'analysesPerMonth': '{count} analiza pisama mjesečno',
      'premiumFeature2': 'AI odgovori i prijevodi',
      'premiumFeature3': 'Arhiva i podsjetnici',
      'proFeature1': 'Za obitelji i male tvrtke',
      'proFeature2': 'Sve iz Premium paketa i viši prag uporabe',
      'restorePurchases': 'Vrati kupnje',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Odaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'U tijeku',
      'doneStatus': 'Završeno',
      'save': 'Spremi',
      'lastUpdated': 'Posljednja izmjena: 26. srpnja 2026.',
      'dataController': 'Voditelj obrade',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'bs': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo uvodnih analiza: {count}.',
      'unlimited': 'Premium analize su aktivne.',
      'monthlyPlanActive': 'Aktivan je vaš mjesečni paket analiza.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili napravite nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Napravi nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja porijekla',
      'addCountry': 'Dodajte zemlju porijekla',
      'signInForProfile': 'Prijavite se da sačuvate profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika/PDF i arhiva ostaju lokalno. Uz vašu saglasnost samo OCR tekst se šalje OpenAI-ju za trenutnu analizu.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'page': 'Stranica',
      'pagesSelected': 'Odabrano stranica: {count}',
      'ocrProgress': 'Prepoznajem stranicu {current} od {total}…',
      'removePage': 'Ukloni stranicu',
      'maxPages': 'Jedno pismo može imati najviše {count} stranica.',
      'filesTooLarge': 'Odabrane stranice su prevelike za ovaj uređaj.',
      'letterText': 'Tekst pisma',
      'ocrReading': 'Prepoznajem tekst lokalno…',
      'loadingImage': 'Učitavam fotografiju…',
      'ocrReady': 'Dokument je učitan i tekst je prepoznat.',
      'ocrNotReady': 'Tekst još nije prepoznat.',
      'photoReadyForAnalysis':
          'Fotografija je učitana. Pritisnite „Analiziraj pismo“.',
      'ocrFailed': 'Dokument nije prepoznat',
      'enterTextFirst': 'Fotografišite dokument ili unesite tekst pisma.',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografišite njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Dobijte podsjetnike za važne datume.',
      'analysisFailed': 'Analiza nije uspjela',
      'sessionExpired': 'Sesija je istekla. Prijavite se ponovo.',
      'tryAgain': 'Pokušajte ponovo.',
      'resultTitle': 'Rezultat analize',
      'simpleExplanation': 'Jednostavno objašnjenje',
      'senderName': 'Pošiljalac / izdavalac',
      'recipientName': 'Primalac pisma ili računa',
      'paymentRecipient': 'Primalac uplate',
      'documentType': 'Vrsta dokumenta',
      'invoiceNumber': 'Broj računa',
      'servicePeriod': 'Period usluge ili obračuna',
      'paymentReference': 'Poziv na broj / svrha uplate',
      'category': 'Kategorija',
      'deadline': 'Rok',
      'amount': 'Pronađen iznos',
      'paymentObligation': 'Obaveza plaćanja',
      'paymentDueDate': 'Rok za plaćanje',
      'paymentOpen': 'Plaćanje je otvoreno',
      'paymentPaid': 'Plaćeno',
      'nextSteps': 'Šta sada trebate uraditi',
      'originalMissing': 'Originalni dokument nije sačuvan uz analizu.',
      'openOriginal': 'Otvori ili preuzmi original',
      'generateReply': 'Generiši odgovor',
      'replyFactsTitle': 'Dodajte svoje objašnjenje',
      'replyFactsHelp':
          'Napišite svojim jezikom šta se dogodilo. AI će to spojiti sa svim stranicama pisma i sastaviti profesionalan odgovor na njemačkom. Unesite samo provjerene činjenice.',
      'replyFactsHint':
          'Npr. objasnite zašto osporavate zahtjev, šta se ranije dogodilo i šta tražite od pošiljaoca…',
      'finishHome': 'Završi i idi na početnu',
      'replyTitle': 'Prijedlog odgovora',
      'formalReply': 'Formalni njemački odgovor',
      'letter': 'Pismo',
      'responseUnavailable': 'Odgovor nije dostupan',
      'replyCopied': 'Odgovor je kopiran.',
      'copyReply': 'Kopiraj odgovor',
      'sendEmail': 'Pošalji e-mail',
      'emailOpenFailed': 'Aplikacija za e-mail nije otvorena',
      'savePdf': 'Sačuvaj PDF',
      'replySavedLocally': 'Odgovor je sačuvan na uređaju za ovaj nalog.',
      'editReplyContext': 'Izmijeni objašnjenje i generiši ponovo',
      'pdfReady': 'PDF je spreman za čuvanje ili dijeljenje.',
      'pdfSaveFailed': 'PDF nije sačuvan',
      'archiveSubtitle': 'Vaša pisma su organizovana po statusu i kategoriji.',
      'deleteDocument': 'Obriši dokument',
      'deleteDocumentBody':
          'Original, OCR tekst i analiza trajno će se obrisati samo sa ovog uređaja.',
      'cancel': 'Odustani',
      'delete': 'Obriši',
      'name': 'Ime',
      'addName': 'Dodajte ime',
      'premiumActive': 'Premium je aktivan',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle':
          'Analize, odgovori i podsjetnici uz odgovornu upotrebu',
      'privacyPolicy': 'Politika privatnosti',
      'terms': 'Uslovi korištenja',
      'exportData': 'Preuzmi moje podatke',
      'exportSubtitle': 'Lokalni JSON izvoz profila, analiza i dokumenata',
      'deleteLocal': 'Obriši lokalnu arhivu',
      'deleteLocalSubtitle': 'Briše samo anonimnu arhivu',
      'deleteLocalBody':
          'Dokumenti, OCR tekst, analize i podsjetnici trajno će se obrisati sa uređaja.',
      'deleteAccount': 'Trajno obriši nalog',
      'deleteAccountQuestion': 'Obrisati nalog?',
      'deleteAccountBody':
          'Ovo trajno briše lokalne dokumente, analize, podsjetnike i nalog.',
      'prepareExport': 'Pripremam privatni izvoz…',
      'exportUnavailable': 'Izvoz trenutno nije dostupan.',
      'choosePlan': 'Izaberite plan',
      'planTagline': 'Više sigurnosti, manje stresa.',
      'freeFeature': '5 uvodnih analiza za novi račun',
      'premiumFeature1': 'Analize uz zaštitu odgovorne upotrebe',
      'analysesPerMonth': '{count} analiza pisama mjesečno',
      'premiumFeature2': 'AI odgovori i prevodi',
      'premiumFeature3': 'Arhiva i podsjetnici',
      'proFeature1': 'Za porodice i male firme',
      'proFeature2': 'Sve iz Premium paketa i viši prag upotrebe',
      'restorePurchases': 'Vrati kupovine',
      'manageSubscription': 'Upravljaj ili otkaži pretplatu',
      'choosePlanButton': 'Izaberi plan',
      'newStatus': 'Novo',
      'progressStatus': 'Rješavam',
      'doneStatus': 'Završeno',
      'save': 'Sačuvaj',
      'lastUpdated': 'Posljednja izmjena: 26. juli 2026.',
      'dataController': 'Kontrolor podataka',
      'contact': 'Kontakt',
      'address': 'Adresa',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'mk': {
      'home': 'Почетна',
      'archive': 'Архива',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добредојдовте',
      'homeSubtitle': 'Разберете ги германските писма на вашиот јазик.',
      'analyzeNew': 'Анализирај ново писмо',
      'remaining': 'Преостанати воведни анализи: {count}.',
      'unlimited': 'Premium анализите се активни.',
      'monthlyPlanActive': 'Вашиот месечен пакет за анализи е активен.',
      'addDocument': 'Додај документ',
      'activatePremium': 'Активирај Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Сè уште немате зачувани писма.',
      'accountCta': 'Најавете се или креирајте сметка',
      'accountCtaSubtitle': 'Сметката ги штити планот и локалната архива.',
      'appLanguage': 'Јазик на апликацијата',
      'signIn': 'Најава',
      'createAccount': 'Креирај сметка',
      'secureLetters': 'Вашата сметка, план и локална архива се одвоени.',
      'email': 'Е-пошта',
      'password': 'Лозинка (најмалку 6 знаци)',
      'continueGoogle': 'Продолжи со Google',
      'continueApple': 'Продолжи со Apple',
      'haveAccount': 'Имате сметка? Најавете се',
      'needAccount': 'Немате сметка? Регистрирајте се',
      'signInFailed': 'Најавата не успеа',
      'myProfile': 'Мој профил',
      'preferredLanguage': 'Претпочитан јазик',
      'country': 'Земја на потекло',
      'addCountry': 'Додајте земја на потекло',
      'signInForProfile': 'Најавете се за да го зачувате профилот',
      'signOut': 'Одјави се',
      'uploadDocument': 'Вчитајте документ',
      'localProcessing':
          'Сликата/PDF и архивата остануваат локално. Со ваша согласност само OCR текстот се испраќа до OpenAI за тековната анализа.',
      'camera': 'Камера',
      'gallery': 'Галерија',
      'pdfImage': 'PDF или слика',
      'page': 'Страница',
      'pagesSelected': 'Избрани страници: {count}',
      'ocrProgress': 'Препознавам страница {current} од {total}…',
      'removePage': 'Отстрани страница',
      'maxPages': 'Едно писмо може да има најмногу {count} страници.',
      'filesTooLarge': 'Избраните страници се преголеми за уредот.',
      'letterText': 'Текст од писмото',
      'ocrReading': 'Го препознавам текстот локално…',
      'loadingImage': 'Ја вчитувам фотографијата…',
      'ocrReady': 'Документот е вчитан и текстот е препознаен.',
      'ocrNotReady': 'Текстот сè уште не е препознаен.',
      'photoReadyForAnalysis':
          'Фотографијата е вчитана. Притиснете „Анализирај писмо“.',
      'ocrFailed': 'Документот не е препознаен',
      'enterTextFirst': 'Фотографирајте документ или внесете текст.',
      'analyzeLetter': 'Анализирај писмо',
      'processing': 'AI обработува…',
      'newAnalysis': 'Нова анализа',
      'assistantTitle': 'AI асистент',
      'assistantHello': 'Здраво! Прашајте ме за последното анализирано писмо.',
      'assistantHint': 'На пр. Кој е рокот?',
      'onboardPhoto': 'Фотографирајте германско писмо',
      'onboardPhotoBody': 'Сликајте документ или вчитајте PDF и слика.',
      'onboardAi': 'AI објаснува што значи',
      'onboardAiBody': 'Јасно објаснување на вашиот јазик.',
      'onboardDeadline': 'Не пропуштајте рокови',
      'onboardDeadlineBody': 'Добивајте потсетници за важни датуми.',
      'analysisFailed': 'Анализата не успеа',
      'sessionExpired': 'Сесијата истече. Најавете се повторно.',
      'tryAgain': 'Обидете се повторно.',
      'resultTitle': 'Резултат од анализата',
      'simpleExplanation': 'Едноставно објаснување',
      'senderName': 'Испраќач / издавач',
      'recipientName': 'Примач на писмото или сметката',
      'paymentRecipient': 'Примач на уплатата',
      'documentType': 'Вид на документ',
      'invoiceNumber': 'Број на сметка',
      'servicePeriod': 'Период на услуга или пресметка',
      'paymentReference': 'Референца / цел на уплатата',
      'category': 'Категорија',
      'deadline': 'Рок',
      'amount': 'Пронајден износ',
      'paymentObligation': 'Обврска за плаќање',
      'paymentDueDate': 'Рок за плаќање',
      'paymentOpen': 'Плаќањето е отворено',
      'paymentPaid': 'Платено',
      'nextSteps': 'Што треба да направите сега',
      'originalMissing': 'Оригиналниот документ не е зачуван со анализата.',
      'openOriginal': 'Отвори или преземи оригинал',
      'generateReply': 'Генерирај одговор',
      'replyFactsTitle': 'Додајте го вашето објаснување',
      'replyFactsHelp':
          'Напишете на вашиот јазик што се случило. AI ќе го спои тоа со сите страници од писмото и ќе состави професионален одговор на германски. Внесете само проверени факти.',
      'replyFactsHint':
          'На пр. објаснете зошто го оспорувате барањето, што се случило претходно и што барате од испраќачот…',
      'finishHome': 'Заврши и оди на почетна',
      'replyTitle': 'Предлог-одговор',
      'formalReply': 'Формален одговор на германски',
      'letter': 'Писмо',
      'responseUnavailable': 'Одговорот не е достапен',
      'replyCopied': 'Одговорот е копиран.',
      'copyReply': 'Копирај одговор',
      'sendEmail': 'Испрати е-пошта',
      'emailOpenFailed': 'Апликацијата за е-пошта не се отвори',
      'savePdf': 'Зачувај PDF',
      'replySavedLocally': 'Одговорот е зачуван на уредот за оваа сметка.',
      'editReplyContext': 'Измени го објаснувањето и генерирај повторно',
      'pdfReady': 'PDF е подготвен за зачувување или споделување.',
      'pdfSaveFailed': 'PDF не е зачуван',
      'archiveSubtitle': 'Вашите писма се организирани по статус и категорија.',
      'deleteDocument': 'Избриши документ',
      'deleteDocumentBody':
          'Оригиналот, OCR текстот и анализата трајно ќе се избришат само од овој уред.',
      'cancel': 'Откажи',
      'delete': 'Избриши',
      'name': 'Име',
      'addName': 'Додајте име',
      'premiumActive': 'Premium е активен',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Анализи, одговори и потсетници со одговорна употреба',
      'privacyPolicy': 'Политика за приватност',
      'terms': 'Услови за користење',
      'exportData': 'Преземи ги моите податоци',
      'exportSubtitle': 'Локален JSON извоз на профил, анализи и документи',
      'deleteLocal': 'Избриши локална архива',
      'deleteLocalSubtitle': 'Ги брише документите само од анонимната архива',
      'deleteLocalBody':
          'Документите, OCR текстот, анализите и потсетниците трајно ќе се избришат од уредот.',
      'deleteAccount': 'Трајно избриши сметка',
      'deleteAccountQuestion': 'Да се избрише сметката?',
      'deleteAccountBody':
          'Ова трајно ги брише локалните документи, анализи, потсетници и сметката.',
      'prepareExport': 'Подготвувам приватен извоз…',
      'exportUnavailable': 'Извозот моментално не е достапен.',
      'choosePlan': 'Изберете план',
      'planTagline': 'Повеќе сигурност, помалку стрес.',
      'freeFeature': '5 воведни анализи за нова сметка',
      'premiumFeature1': 'Анализи со заштита на одговорна употреба',
      'analysesPerMonth': '{count} анализи на писма месечно',
      'premiumFeature2': 'AI одговори и преводи',
      'premiumFeature3': 'Архива и потсетници',
      'proFeature1': 'За семејства и мали фирми',
      'proFeature2': 'Сè од Premium и повисок праг',
      'restorePurchases': 'Врати купувања',
      'manageSubscription': 'Управувај или откажи претплата',
      'choosePlanButton': 'Избери план',
      'newStatus': 'Ново',
      'progressStatus': 'Во тек',
      'doneStatus': 'Завршено',
      'save': 'Зачувај',
      'lastUpdated': 'Последна измена: 26 јули 2026.',
      'dataController': 'Контролор на податоци',
      'contact': 'Контакт',
      'address': 'Адреса',
      'next': 'Продолжи',
      'start': 'Започни безбедно',
      'skip': 'Прескокни',
    },
    'de': {
      'home': 'Start',
      'archive': 'Archiv',
      'assistant': 'Assistent',
      'profile': 'Profil',
      'welcome': 'Willkommen',
      'homeSubtitle': 'Verstehen Sie deutsche Briefe in Ihrer Sprache.',
      'analyzeNew': 'Neuen Brief analysieren',
      'remaining': 'Noch {count} Einführungsanalysen.',
      'unlimited': 'Premium-Analysen sind aktiv.',
      'monthlyPlanActive': 'Ihr monatliches Analysepaket ist aktiv.',
      'addDocument': 'Dokument hinzufügen',
      'activatePremium': 'Premium aktivieren',
      'recentLetters': 'Letzte Briefe',
      'emptyLetters': 'Noch keine Briefe gespeichert.',
      'accountCta': 'Anmelden oder Konto erstellen',
      'accountCtaSubtitle':
          'Ihr Konto schützt Tarif und getrenntes lokales Archiv.',
      'appLanguage': 'App-Sprache',
      'signIn': 'Anmelden',
      'createAccount': 'Konto erstellen',
      'secureLetters': 'Konto, Tarif und lokales Archiv bleiben getrennt.',
      'email': 'E-Mail',
      'password': 'Passwort (mindestens 6 Zeichen)',
      'continueGoogle': 'Mit Google fortfahren',
      'continueApple': 'Mit Apple fortfahren',
      'haveAccount': 'Bereits registriert? Anmelden',
      'needAccount': 'Noch kein Konto? Registrieren',
      'signInFailed': 'Anmeldung fehlgeschlagen',
      'myProfile': 'Mein Profil',
      'preferredLanguage': 'Bevorzugte Sprache',
      'country': 'Herkunftsland',
      'addCountry': 'Herkunftsland hinzufügen',
      'signInForProfile': 'Zum Speichern des Profils anmelden',
      'signOut': 'Abmelden',
      'uploadDocument': 'Dokument hochladen',
      'localProcessing':
          'Bild/PDF und Archiv bleiben lokal. Mit Ihrer Einwilligung wird nur der OCR-Text für die aktuelle Analyse an OpenAI gesendet.',
      'camera': 'Kamera',
      'gallery': 'Galerie',
      'pdfImage': 'PDF oder Bild',
      'page': 'Seite',
      'pagesSelected': '{count} Seiten ausgewählt',
      'ocrProgress': 'Seite {current} von {total} wird erkannt…',
      'removePage': 'Seite entfernen',
      'maxPages': 'Ein Schreiben kann höchstens {count} Seiten haben.',
      'filesTooLarge': 'Die ausgewählten Seiten sind für dieses Gerät zu groß.',
      'letterText': 'Brieftext',
      'ocrReading': 'Text wird lokal erkannt…',
      'loadingImage': 'Foto wird geladen…',
      'ocrReady': 'Dokument geladen und Text erkannt.',
      'ocrNotReady': 'Text wurde noch nicht erkannt.',
      'photoReadyForAnalysis':
          'Das Foto ist geladen. Tippen Sie auf „Schreiben analysieren“.',
      'ocrFailed': 'Dokument wurde nicht erkannt',
      'enterTextFirst': 'Dokument fotografieren oder Brieftext eingeben.',
      'analyzeLetter': 'Brief analysieren',
      'processing': 'KI verarbeitet…',
      'newAnalysis': 'Neue Analyse',
      'assistantTitle': 'KI-Assistent',
      'assistantHello':
          'Hallo! Fragen Sie mich zum zuletzt analysierten Brief.',
      'assistantHint': 'Z. B. Welche Frist gilt?',
      'onboardPhoto': 'Deutschen Brief fotografieren',
      'onboardPhotoBody': 'Dokument aufnehmen oder PDF/Bild laden.',
      'onboardAi': 'KI erklärt die Bedeutung',
      'onboardAiBody': 'Klare Erklärung in Ihrer Sprache.',
      'onboardDeadline': 'Keine Frist verpassen',
      'onboardDeadlineBody': 'Erinnerungen für wichtige Termine erhalten.',
      'analysisFailed': 'Analyse fehlgeschlagen',
      'sessionExpired': 'Die Sitzung ist abgelaufen. Bitte erneut anmelden.',
      'tryAgain': 'Bitte versuchen Sie es erneut.',
      'resultTitle': 'Analyseergebnis',
      'simpleExplanation': 'Einfache Erklärung',
      'senderName': 'Absender / Rechnungssteller',
      'recipientName': 'Brief- oder Rechnungsempfänger',
      'paymentRecipient': 'Zahlungsempfänger',
      'documentType': 'Dokumentart',
      'invoiceNumber': 'Rechnungsnummer',
      'servicePeriod': 'Leistungs- oder Abrechnungszeitraum',
      'paymentReference': 'Verwendungszweck / Zahlungsreferenz',
      'category': 'Kategorie',
      'deadline': 'Frist',
      'amount': 'Gefundener Betrag',
      'paymentObligation': 'Zahlungsverpflichtung',
      'paymentDueDate': 'Zahlungsfrist',
      'paymentOpen': 'Zahlung offen',
      'paymentPaid': 'Bezahlt',
      'nextSteps': 'Was Sie jetzt tun sollten',
      'originalMissing': 'Das Originaldokument wurde nicht gespeichert.',
      'openOriginal': 'Original öffnen oder herunterladen',
      'generateReply': 'Antwort erstellen',
      'replyFactsTitle': 'Ihre Erklärung ergänzen',
      'replyFactsHelp':
          'Schildern Sie in Ihrer Sprache, was passiert ist. Die KI verbindet diese Angaben mit allen Seiten des Schreibens und erstellt eine professionelle deutsche Antwort. Geben Sie nur überprüfte Tatsachen an.',
      'replyFactsHint':
          'Z. B. warum Sie die Forderung bestreiten, was zuvor geschehen ist und was Sie vom Absender verlangen…',
      'finishHome': 'Fertig und zur Startseite',
      'replyTitle': 'Antwortvorschlag',
      'formalReply': 'Formelle deutsche Antwort',
      'letter': 'Brief',
      'responseUnavailable': 'Antwort nicht verfügbar',
      'replyCopied': 'Antwort kopiert.',
      'copyReply': 'Antwort kopieren',
      'sendEmail': 'E-Mail senden',
      'emailOpenFailed': 'Die E-Mail-App konnte nicht geöffnet werden',
      'savePdf': 'PDF speichern',
      'replySavedLocally':
          'Die Antwort wurde für dieses Konto lokal gespeichert.',
      'editReplyContext': 'Erklärung bearbeiten und neu erstellen',
      'pdfReady': 'Die PDF kann jetzt gespeichert oder geteilt werden.',
      'pdfSaveFailed': 'PDF konnte nicht gespeichert werden',
      'archiveSubtitle': 'Ihre Briefe sind nach Status und Kategorie geordnet.',
      'deleteDocument': 'Dokument löschen',
      'deleteDocumentBody':
          'Original, OCR-Text und Analyse werden nur auf diesem Gerät dauerhaft gelöscht.',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'name': 'Name',
      'addName': 'Name hinzufügen',
      'premiumActive': 'Premium ist aktiv',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle':
          'Analysen, Antworten und Erinnerungen bei fairer Nutzung',
      'privacyPolicy': 'Datenschutzerklärung',
      'terms': 'Nutzungsbedingungen',
      'exportData': 'Meine Daten herunterladen',
      'exportSubtitle':
          'Lokaler JSON-Export von Profil, Analysen und Dokumenten',
      'deleteLocal': 'Lokales Archiv löschen',
      'deleteLocalSubtitle': 'Löscht nur Dokumente aus dem anonymen Archiv',
      'deleteLocalBody':
          'Dokumente, OCR-Text, Analysen und Erinnerungen werden dauerhaft vom Gerät gelöscht.',
      'deleteAccount': 'Konto dauerhaft löschen',
      'deleteAccountQuestion': 'Konto löschen?',
      'deleteAccountBody':
          'Dadurch werden lokale Dokumente, Analysen, Erinnerungen und das Konto dauerhaft gelöscht.',
      'prepareExport': 'Privater Datenexport wird vorbereitet…',
      'exportUnavailable': 'Datenexport ist derzeit nicht verfügbar.',
      'choosePlan': 'Tarif auswählen',
      'planTagline': 'Mehr Sicherheit, weniger Stress.',
      'freeFeature': '5 Einführungsanalysen für neue Konten',
      'premiumFeature1': 'Analysen mit Schutz vor missbräuchlicher Nutzung',
      'analysesPerMonth': '{count} Briefanalysen pro Monat',
      'premiumFeature2': 'KI-Antworten und Übersetzungen',
      'premiumFeature3': 'Archiv und Erinnerungen',
      'proFeature1': 'Für Familien und kleine Unternehmen',
      'proFeature2': 'Alles aus Premium mit höherem Nutzungslimit',
      'restorePurchases': 'Käufe wiederherstellen',
      'manageSubscription': 'Abo verwalten oder kündigen',
      'choosePlanButton': 'Tarif wählen',
      'newStatus': 'Neu',
      'progressStatus': 'In Bearbeitung',
      'doneStatus': 'Erledigt',
      'save': 'Speichern',
      'lastUpdated': 'Letzte Änderung: 26. Juli 2026.',
      'dataController': 'Verantwortlicher',
      'contact': 'Kontakt',
      'address': 'Adresse',
      'next': 'Weiter',
      'start': 'Sicher starten',
      'skip': 'Überspringen',
    },
    'en': {
      'home': 'Home',
      'archive': 'Archive',
      'assistant': 'Assistant',
      'profile': 'Profile',
      'welcome': 'Welcome',
      'homeSubtitle': 'Understand German letters in the language you prefer.',
      'analyzeNew': 'Analyze a new letter',
      'remaining': '{count} introductory analyses remaining.',
      'unlimited': 'Premium analyses are active.',
      'monthlyPlanActive': 'Your monthly analysis plan is active.',
      'addDocument': 'Add document',
      'activatePremium': 'Activate Premium',
      'recentLetters': 'Recent letters',
      'emptyLetters': 'No saved letters yet.',
      'accountCta': 'Sign in or create an account',
      'accountCtaSubtitle':
          'Your account protects your plan and separate local archive.',
      'appLanguage': 'App language',
      'signIn': 'Sign in',
      'createAccount': 'Create account',
      'secureLetters': 'Your account, plan and local archive remain separate.',
      'email': 'Email',
      'password': 'Password (at least 6 characters)',
      'continueGoogle': 'Continue with Google',
      'continueApple': 'Continue with Apple',
      'haveAccount': 'Already have an account? Sign in',
      'needAccount': 'No account? Register',
      'signInFailed': 'Sign-in failed',
      'myProfile': 'My profile',
      'preferredLanguage': 'Preferred language',
      'country': 'Country of origin',
      'addCountry': 'Add country of origin',
      'signInForProfile': 'Sign in to save your profile',
      'signOut': 'Sign out',
      'uploadDocument': 'Upload document',
      'localProcessing':
          'Images/PDFs and the archive stay local. With your consent, only OCR text is sent to OpenAI for the current analysis.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pdfImage': 'PDF or image',
      'page': 'Page',
      'pagesSelected': '{count} pages selected',
      'ocrProgress': 'Recognizing page {current} of {total}…',
      'removePage': 'Remove page',
      'maxPages': 'One letter can contain up to {count} pages.',
      'filesTooLarge': 'The selected pages are too large for this device.',
      'letterText': 'Letter text',
      'ocrReading': 'Recognizing text locally…',
      'loadingImage': 'Loading photo…',
      'ocrReady': 'Document loaded and text recognized.',
      'ocrNotReady': 'Text has not been recognized yet.',
      'photoReadyForAnalysis': 'The photo is loaded. Tap “Analyse letter”.',
      'ocrFailed': 'Document was not recognized',
      'enterTextFirst': 'Photograph a document or enter the letter text.',
      'analyzeLetter': 'Analyze letter',
      'processing': 'AI is processing…',
      'newAnalysis': 'New analysis',
      'assistantTitle': 'AI assistant',
      'assistantHello':
          'Hello! Ask me about the most recently analyzed letter.',
      'assistantHint': 'For example: What is the deadline?',
      'onboardPhoto': 'Photograph a German letter',
      'onboardPhotoBody': 'Capture a document or upload a PDF or image.',
      'onboardAi': 'AI explains what it means',
      'onboardAiBody': 'A clear explanation in your language.',
      'onboardDeadline': 'Never miss a deadline',
      'onboardDeadlineBody': 'Receive reminders for important dates.',
      'analysisFailed': 'Analysis failed',
      'sessionExpired': 'Your session has expired. Please sign in again.',
      'tryAgain': 'Please try again.',
      'resultTitle': 'Analysis result',
      'simpleExplanation': 'Plain-language explanation',
      'senderName': 'Sender / invoice issuer',
      'recipientName': 'Letter or invoice recipient',
      'paymentRecipient': 'Payment recipient',
      'documentType': 'Document type',
      'invoiceNumber': 'Invoice number',
      'servicePeriod': 'Service or billing period',
      'paymentReference': 'Payment reference',
      'category': 'Category',
      'deadline': 'Deadline',
      'amount': 'Amount found',
      'paymentObligation': 'Payment obligation',
      'paymentDueDate': 'Payment due date',
      'paymentOpen': 'Payment outstanding',
      'paymentPaid': 'Paid',
      'nextSteps': 'What to do next',
      'originalMissing':
          'The original document was not saved with this analysis.',
      'openOriginal': 'Open or download original',
      'generateReply': 'Generate reply',
      'replyFactsTitle': 'Add your explanation',
      'replyFactsHelp':
          'Describe what happened in your own language. AI will combine it with every page of the letter and draft a professional German response. Include only facts you can verify.',
      'replyFactsHint':
          'For example, explain why you dispute the claim, what happened earlier, and what you want the sender to do…',
      'finishHome': 'Finish and go home',
      'replyTitle': 'Suggested reply',
      'formalReply': 'Formal German reply',
      'letter': 'Letter',
      'responseUnavailable': 'Reply unavailable',
      'replyCopied': 'Reply copied.',
      'copyReply': 'Copy reply',
      'sendEmail': 'Send email',
      'emailOpenFailed': 'The email app could not be opened',
      'savePdf': 'Save PDF',
      'replySavedLocally':
          'The reply is saved on this device for this account.',
      'editReplyContext': 'Edit explanation and generate again',
      'pdfReady': 'The PDF is ready to save or share.',
      'pdfSaveFailed': 'PDF could not be saved',
      'archiveSubtitle': 'Your letters are organized by status and category.',
      'deleteDocument': 'Delete document',
      'deleteDocumentBody':
          'The original, OCR text and analysis will be permanently deleted from this device only.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'name': 'Name',
      'addName': 'Add name',
      'premiumActive': 'Premium is active',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Analyses, replies and reminders with responsible use',
      'privacyPolicy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'exportData': 'Download my data',
      'exportSubtitle': 'Local JSON export of profile, analyses and documents',
      'deleteLocal': 'Delete local archive',
      'deleteLocalSubtitle':
          'Deletes documents from the anonymous archive only',
      'deleteLocalBody':
          'Documents, OCR text, analyses and reminders will be permanently deleted from this device.',
      'deleteAccount': 'Permanently delete account',
      'deleteAccountQuestion': 'Delete account?',
      'deleteAccountBody':
          'This permanently deletes local documents, analyses, reminders and the user account.',
      'prepareExport': 'Preparing private data export…',
      'exportUnavailable': 'Data export is currently unavailable.',
      'choosePlan': 'Choose a plan',
      'planTagline': 'More confidence, less stress.',
      'freeFeature': '5 introductory analyses for new accounts',
      'premiumFeature1': 'Analyses with responsible-use protection',
      'analysesPerMonth': '{count} letter analyses per month',
      'premiumFeature2': 'AI replies and translations',
      'premiumFeature3': 'Archive and reminders',
      'proFeature1': 'For families and small businesses',
      'proFeature2': 'Everything in Premium with a higher usage threshold',
      'restorePurchases': 'Restore purchases',
      'manageSubscription': 'Manage or cancel subscription',
      'choosePlanButton': 'Choose plan',
      'newStatus': 'New',
      'progressStatus': 'In progress',
      'doneStatus': 'Done',
      'save': 'Save',
      'lastUpdated': 'Last updated: July 26, 2026.',
      'dataController': 'Data controller',
      'contact': 'Contact',
      'address': 'Address',
      'next': 'Continue',
      'start': 'Start securely',
      'skip': 'Skip',
    },
    'bg': {
      'home': 'Начало',
      'archive': 'Архив',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добре дошли',
      'homeSubtitle': 'Разбирайте немските писма на предпочитания от вас език.',
      'analyzeNew': 'Анализирай ново писмо',
      'remaining': 'Остават {count} безплатни въвеждащи анализа.',
      'unlimited': 'Premium анализите са активни.',
      'monthlyPlanActive': 'Месечният ви пакет за анализи е активен.',
      'addDocument': 'Добави документ',
      'activatePremium': 'Активирай Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Все още няма запазени писма.',
      'accountCta': 'Влезте или създайте акаунт',
      'accountCtaSubtitle': 'Акаунтът пази плана и отделния локален архив.',
      'appLanguage': 'Език на приложението',
      'signIn': 'Вход',
      'createAccount': 'Създай акаунт',
      'secureLetters': 'Акаунтът, планът и локалният архив остават отделни.',
      'email': 'Имейл',
      'password': 'Парола (поне 6 знака)',
      'continueGoogle': 'Продължи с Google',
      'continueApple': 'Продължи с Apple',
      'haveAccount': 'Имате акаунт? Влезте',
      'needAccount': 'Нямате акаунт? Регистрирайте се',
      'signInFailed': 'Входът е неуспешен',
      'myProfile': 'Моят профил',
      'preferredLanguage': 'Предпочитан език',
      'country': 'Държава на произход',
      'addCountry': 'Добавете държава на произход',
      'signInForProfile': 'Влезте, за да запазите профила',
      'signOut': 'Изход',
      'uploadDocument': 'Качете документ',
      'localProcessing':
          'Изображението/PDF и архивът остават локално. С ваше съгласие само OCR текстът се изпраща до OpenAI за текущия анализ.',
      'camera': 'Камера',
      'gallery': 'Галерия',
      'pdfImage': 'PDF или изображение',
      'page': 'Страница',
      'pagesSelected': 'Избрани страници: {count}',
      'ocrProgress': 'Разпознавам страница {current} от {total}…',
      'removePage': 'Премахни страницата',
      'maxPages': 'Едно писмо може да съдържа до {count} страници.',
      'filesTooLarge': 'Избраните страници са твърде големи за устройството.',
      'letterText': 'Текст на писмото',
      'ocrReading': 'Разпознавам текста локално…',
      'loadingImage': 'Зареждам снимката…',
      'ocrReady': 'Документът е зареден и текстът е разпознат.',
      'ocrNotReady': 'Текстът все още не е разпознат.',
      'photoReadyForAnalysis':
          'Снимката е заредена. Натиснете „Анализирай писмото“.',
      'ocrFailed': 'Документът не е разпознат',
      'enterTextFirst': 'Снимайте документ или въведете текста.',
      'analyzeLetter': 'Анализирай писмо',
      'processing': 'AI обработва…',
      'newAnalysis': 'Нов анализ',
      'assistantTitle': 'AI асистент',
      'assistantHello':
          'Здравейте! Попитайте ме за последното анализирано писмо.',
      'assistantHint': 'Напр. Какъв е срокът?',
      'onboardPhoto': 'Снимайте немско писмо',
      'onboardPhotoBody': 'Снимайте документ или качете PDF/изображение.',
      'onboardAi': 'AI обяснява значението',
      'onboardAiBody': 'Ясно обяснение на вашия език.',
      'onboardDeadline': 'Не пропускайте срокове',
      'onboardDeadlineBody': 'Получавайте напомняния за важни дати.',
      'analysisFailed': 'Анализът е неуспешен',
      'sessionExpired': 'Сесията изтече. Влезте отново.',
      'tryAgain': 'Опитайте отново.',
      'resultTitle': 'Резултат от анализа',
      'simpleExplanation': 'Обяснение на разбираем език',
      'senderName': 'Подател / издател',
      'recipientName': 'Получател на писмото или фактурата',
      'paymentRecipient': 'Получател на плащането',
      'documentType': 'Вид документ',
      'invoiceNumber': 'Номер на фактура',
      'servicePeriod': 'Период на услугата или отчитане',
      'paymentReference': 'Основание / референция за плащане',
      'category': 'Категория',
      'deadline': 'Срок',
      'amount': 'Открита сума',
      'paymentObligation': 'Задължение за плащане',
      'paymentDueDate': 'Срок за плащане',
      'paymentOpen': 'Плащането е неприключено',
      'paymentPaid': 'Платено',
      'nextSteps': 'Какво да направите сега',
      'originalMissing': 'Оригиналният документ не е запазен с анализа.',
      'openOriginal': 'Отвори или изтегли оригинала',
      'generateReply': 'Генерирай отговор',
      'replyFactsTitle': 'Добавете вашето обяснение',
      'replyFactsHelp':
          'Опишете на своя език какво се е случило. AI ще го съчетае с всички страници на писмото и ще изготви професионален отговор на немски. Въведете само проверени факти.',
      'replyFactsHint':
          'Напр. обяснете защо оспорвате искането, какво се е случило по-рано и какво искате от подателя…',
      'finishHome': 'Завърши и към началото',
      'replyTitle': 'Предложен отговор',
      'formalReply': 'Официален отговор на немски',
      'letter': 'Писмо',
      'responseUnavailable': 'Отговорът не е достъпен',
      'replyCopied': 'Отговорът е копиран.',
      'copyReply': 'Копирай отговор',
      'sendEmail': 'Изпрати имейл',
      'emailOpenFailed': 'Приложението за имейл не се отвори',
      'savePdf': 'Запази PDF',
      'replySavedLocally':
          'Отговорът е запазен на устройството за този профил.',
      'editReplyContext': 'Редактирай обяснението и генерирай отново',
      'pdfReady': 'PDF файлът е готов за запазване или споделяне.',
      'pdfSaveFailed': 'PDF файлът не бе запазен',
      'archiveSubtitle': 'Писмата са организирани по статус и категория.',
      'deleteDocument': 'Изтрий документ',
      'deleteDocumentBody':
          'Оригиналът, OCR текстът и анализът ще бъдат изтрити само от това устройство.',
      'cancel': 'Отказ',
      'delete': 'Изтрий',
      'name': 'Име',
      'addName': 'Добавете име',
      'premiumActive': 'Premium е активен',
      'premiumName': 'BriefAI Premium',
      'premiumSubtitle': 'Анализи, отговори и напомняния с отговорна употреба',
      'privacyPolicy': 'Политика за поверителност',
      'terms': 'Условия за ползване',
      'exportData': 'Изтегли моите данни',
      'exportSubtitle': 'Локален JSON експорт на профил, анализи и документи',
      'deleteLocal': 'Изтрий локалния архив',
      'deleteLocalSubtitle': 'Изтрива само анонимния архив',
      'deleteLocalBody':
          'Документите, OCR текстът, анализите и напомнянията ще бъдат изтрити от устройството.',
      'deleteAccount': 'Изтрий акаунта завинаги',
      'deleteAccountQuestion': 'Да се изтрие ли акаунтът?',
      'deleteAccountBody':
          'Това изтрива завинаги локалните документи, анализи, напомняния и акаунта.',
      'prepareExport': 'Подготвям частен експорт…',
      'exportUnavailable': 'Експортът в момента не е достъпен.',
      'choosePlan': 'Изберете план',
      'planTagline': 'Повече сигурност, по-малко стрес.',
      'freeFeature': '5 въвеждащи анализа за нови акаунти',
      'premiumFeature1': 'Анализи със защита за отговорна употреба',
      'analysesPerMonth': '{count} анализа на писма месечно',
      'premiumFeature2': 'AI отговори и преводи',
      'premiumFeature3': 'Архив и напомняния',
      'proFeature1': 'За семейства и малки фирми',
      'proFeature2': 'Всичко от Premium с по-висок праг',
      'restorePurchases': 'Възстанови покупки',
      'manageSubscription': 'Управлявай или откажи абонамента',
      'choosePlanButton': 'Избери план',
      'newStatus': 'Ново',
      'progressStatus': 'В процес',
      'doneStatus': 'Завършено',
      'save': 'Запази',
      'lastUpdated': 'Последна промяна: 26 юли 2026 г.',
      'dataController': 'Администратор на данни',
      'contact': 'Контакт',
      'address': 'Адрес',
      'next': 'Продължи',
      'start': 'Започни сигурно',
      'skip': 'Пропусни',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) async => AppStrings(locale);

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
