import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('sr'),
    Locale('hr'),
    Locale('bs'),
    Locale('mk'),
    Locale('de'),
    Locale('en'),
    Locale('bg'),
  ];

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings) ??
      const AppStrings(Locale('sr'));

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['sr']!)[key] ??
      _values['sr']![key] ??
      key;

  String remaining(int value) =>
      text('remaining').replaceFirst('{count}', value.toString());

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  static const _values = <String, Map<String, String>>{
    'sr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumite nemačka pisma, na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 2 besplatne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Poslednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili kreirajte nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Kreiraj nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi sa Google',
      'continueApple': 'Nastavi sa Apple',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Preferirani jezik',
      'country': 'Zemlja porekla',
      'addCountry': 'Dodajte zemlju porekla',
      'signInForProfile': 'Prijavite se da biste sačuvali profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika ili PDF obrađuju se lokalno. Original i arhiva se ne šalju u Firebase.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst sa pisma',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o poslednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografiši nemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propusti rokove',
      'onboardDeadlineBody': 'Dobijte podsetnike za važne datume.',
      'next': 'Nastavi',
      'start': 'Počni bezbedno',
      'skip': 'Preskoči',
    },
    'hr': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 2 besplatne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate spremljenih pisama.',
      'accountCta': 'Prijavite se ili izradite račun',
      'accountCtaSubtitle': 'Račun štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Izradi račun',
      'secureLetters': 'Vaš račun, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'E-pošta',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate račun? Prijavite se',
      'needAccount': 'Nemate račun? Registrirajte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja podrijetla',
      'addCountry': 'Dodajte zemlju podrijetla',
      'signInForProfile': 'Prijavite se za spremanje profila',
      'signOut': 'Odjava',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika ili PDF obrađuju se lokalno. Original i arhiva ne šalju se u Firebase.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst pisma',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Pozdrav! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografirajte njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava značenje',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Primajte podsjetnike za važne datume.',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'bs': {
      'home': 'Početna',
      'archive': 'Arhiva',
      'assistant': 'Asistent',
      'profile': 'Profil',
      'welcome': 'Dobro došli',
      'homeSubtitle': 'Razumijte njemačka pisma na jeziku koji vam odgovara.',
      'analyzeNew': 'Analiziraj novo pismo',
      'remaining': 'Preostalo: {count} od 2 besplatne analize.',
      'unlimited': 'Premium analize su aktivne.',
      'addDocument': 'Dodaj dokument',
      'activatePremium': 'Aktiviraj Premium',
      'recentLetters': 'Posljednja pisma',
      'emptyLetters': 'Još nemate sačuvanih pisama.',
      'accountCta': 'Prijavite se ili napravite nalog',
      'accountCtaSubtitle': 'Nalog štiti plan i odvojenu lokalnu arhivu.',
      'appLanguage': 'Jezik aplikacije',
      'signIn': 'Prijava',
      'createAccount': 'Napravi nalog',
      'secureLetters': 'Vaš nalog, plan i lokalna arhiva ostaju odvojeni.',
      'email': 'Email',
      'password': 'Lozinka (najmanje 6 znakova)',
      'continueGoogle': 'Nastavi s Googleom',
      'continueApple': 'Nastavi s Appleom',
      'haveAccount': 'Već imate nalog? Prijavite se',
      'needAccount': 'Nemate nalog? Registrujte se',
      'signInFailed': 'Prijava nije uspjela',
      'myProfile': 'Moj profil',
      'preferredLanguage': 'Željeni jezik',
      'country': 'Zemlja porijekla',
      'addCountry': 'Dodajte zemlju porijekla',
      'signInForProfile': 'Prijavite se da sačuvate profil',
      'signOut': 'Odjavi se',
      'uploadDocument': 'Učitajte dokument',
      'localProcessing':
          'Slika ili PDF obrađuju se lokalno. Original i arhiva ne šalju se u Firebase.',
      'camera': 'Kamera',
      'gallery': 'Galerija',
      'pdfImage': 'PDF ili slika',
      'letterText': 'Tekst pisma',
      'analyzeLetter': 'Analiziraj pismo',
      'processing': 'AI obrađuje…',
      'newAnalysis': 'Nova analiza',
      'assistantTitle': 'AI asistent',
      'assistantHello': 'Zdravo! Pitajte me o posljednjem analiziranom pismu.',
      'assistantHint': 'Npr. Koji je rok?',
      'onboardPhoto': 'Fotografišite njemačko pismo',
      'onboardPhotoBody': 'Snimite dokument ili učitajte PDF i sliku.',
      'onboardAi': 'AI objašnjava šta znači',
      'onboardAiBody': 'Jasno objašnjenje na vašem jeziku.',
      'onboardDeadline': 'Ne propustite rokove',
      'onboardDeadlineBody': 'Dobijte podsjetnike za važne datume.',
      'next': 'Nastavi',
      'start': 'Počni sigurno',
      'skip': 'Preskoči',
    },
    'mk': {
      'home': 'Почетна',
      'archive': 'Архива',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добредојдовте',
      'homeSubtitle': 'Разберете ги германските писма на вашиот јазик.',
      'analyzeNew': 'Анализирај ново писмо',
      'remaining': 'Преостануваат {count} од 2 бесплатни анализи.',
      'unlimited': 'Premium анализите се активни.',
      'addDocument': 'Додај документ',
      'activatePremium': 'Активирај Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Сè уште немате зачувани писма.',
      'accountCta': 'Најавете се или креирајте сметка',
      'accountCtaSubtitle': 'Сметката ги штити планот и локалната архива.',
      'appLanguage': 'Јазик на апликацијата',
      'signIn': 'Најава',
      'createAccount': 'Креирај сметка',
      'secureLetters': 'Вашата сметка, план и локална архива се одвоени.',
      'email': 'Е-пошта',
      'password': 'Лозинка (најмалку 6 знаци)',
      'continueGoogle': 'Продолжи со Google',
      'continueApple': 'Продолжи со Apple',
      'haveAccount': 'Имате сметка? Најавете се',
      'needAccount': 'Немате сметка? Регистрирајте се',
      'signInFailed': 'Најавата не успеа',
      'myProfile': 'Мој профил',
      'preferredLanguage': 'Претпочитан јазик',
      'country': 'Земја на потекло',
      'addCountry': 'Додајте земја на потекло',
      'signInForProfile': 'Најавете се за да го зачувате профилот',
      'signOut': 'Одјави се',
      'uploadDocument': 'Вчитајте документ',
      'localProcessing':
          'Сликата или PDF се обработуваат локално. Оригиналот и архивата не се праќаат во Firebase.',
      'camera': 'Камера',
      'gallery': 'Галерија',
      'pdfImage': 'PDF или слика',
      'letterText': 'Текст од писмото',
      'analyzeLetter': 'Анализирај писмо',
      'processing': 'AI обработува…',
      'newAnalysis': 'Нова анализа',
      'assistantTitle': 'AI асистент',
      'assistantHello': 'Здраво! Прашајте ме за последното анализирано писмо.',
      'assistantHint': 'На пр. Кој е рокот?',
      'onboardPhoto': 'Фотографирајте германско писмо',
      'onboardPhotoBody': 'Сликајте документ или вчитајте PDF и слика.',
      'onboardAi': 'AI објаснува што значи',
      'onboardAiBody': 'Јасно објаснување на вашиот јазик.',
      'onboardDeadline': 'Не пропуштајте рокови',
      'onboardDeadlineBody': 'Добивајте потсетници за важни датуми.',
      'next': 'Продолжи',
      'start': 'Започни безбедно',
      'skip': 'Прескокни',
    },
    'de': {
      'home': 'Start',
      'archive': 'Archiv',
      'assistant': 'Assistent',
      'profile': 'Profil',
      'welcome': 'Willkommen',
      'homeSubtitle': 'Verstehen Sie deutsche Briefe in Ihrer Sprache.',
      'analyzeNew': 'Neuen Brief analysieren',
      'remaining': 'Noch {count} von 2 kostenlosen Analysen.',
      'unlimited': 'Premium-Analysen sind aktiv.',
      'addDocument': 'Dokument hinzufügen',
      'activatePremium': 'Premium aktivieren',
      'recentLetters': 'Letzte Briefe',
      'emptyLetters': 'Noch keine Briefe gespeichert.',
      'accountCta': 'Anmelden oder Konto erstellen',
      'accountCtaSubtitle':
          'Ihr Konto schützt Tarif und getrenntes lokales Archiv.',
      'appLanguage': 'App-Sprache',
      'signIn': 'Anmelden',
      'createAccount': 'Konto erstellen',
      'secureLetters': 'Konto, Tarif und lokales Archiv bleiben getrennt.',
      'email': 'E-Mail',
      'password': 'Passwort (mindestens 6 Zeichen)',
      'continueGoogle': 'Mit Google fortfahren',
      'continueApple': 'Mit Apple fortfahren',
      'haveAccount': 'Bereits registriert? Anmelden',
      'needAccount': 'Noch kein Konto? Registrieren',
      'signInFailed': 'Anmeldung fehlgeschlagen',
      'myProfile': 'Mein Profil',
      'preferredLanguage': 'Bevorzugte Sprache',
      'country': 'Herkunftsland',
      'addCountry': 'Herkunftsland hinzufügen',
      'signInForProfile': 'Zum Speichern des Profils anmelden',
      'signOut': 'Abmelden',
      'uploadDocument': 'Dokument hochladen',
      'localProcessing':
          'Bild oder PDF werden lokal verarbeitet. Original und Archiv werden nicht an Firebase gesendet.',
      'camera': 'Kamera',
      'gallery': 'Galerie',
      'pdfImage': 'PDF oder Bild',
      'letterText': 'Brieftext',
      'analyzeLetter': 'Brief analysieren',
      'processing': 'KI verarbeitet…',
      'newAnalysis': 'Neue Analyse',
      'assistantTitle': 'KI-Assistent',
      'assistantHello':
          'Hallo! Fragen Sie mich zum zuletzt analysierten Brief.',
      'assistantHint': 'Z. B. Welche Frist gilt?',
      'onboardPhoto': 'Deutschen Brief fotografieren',
      'onboardPhotoBody': 'Dokument aufnehmen oder PDF/Bild laden.',
      'onboardAi': 'KI erklärt die Bedeutung',
      'onboardAiBody': 'Klare Erklärung in Ihrer Sprache.',
      'onboardDeadline': 'Keine Frist verpassen',
      'onboardDeadlineBody': 'Erinnerungen für wichtige Termine erhalten.',
      'next': 'Weiter',
      'start': 'Sicher starten',
      'skip': 'Überspringen',
    },
    'en': {
      'home': 'Home',
      'archive': 'Archive',
      'assistant': 'Assistant',
      'profile': 'Profile',
      'welcome': 'Welcome',
      'homeSubtitle': 'Understand German letters in the language you prefer.',
      'analyzeNew': 'Analyze a new letter',
      'remaining': '{count} of 2 free analyses remaining.',
      'unlimited': 'Premium analyses are active.',
      'addDocument': 'Add document',
      'activatePremium': 'Activate Premium',
      'recentLetters': 'Recent letters',
      'emptyLetters': 'No saved letters yet.',
      'accountCta': 'Sign in or create an account',
      'accountCtaSubtitle':
          'Your account protects your plan and separate local archive.',
      'appLanguage': 'App language',
      'signIn': 'Sign in',
      'createAccount': 'Create account',
      'secureLetters': 'Your account, plan and local archive remain separate.',
      'email': 'Email',
      'password': 'Password (at least 6 characters)',
      'continueGoogle': 'Continue with Google',
      'continueApple': 'Continue with Apple',
      'haveAccount': 'Already have an account? Sign in',
      'needAccount': 'No account? Register',
      'signInFailed': 'Sign-in failed',
      'myProfile': 'My profile',
      'preferredLanguage': 'Preferred language',
      'country': 'Country of origin',
      'addCountry': 'Add country of origin',
      'signInForProfile': 'Sign in to save your profile',
      'signOut': 'Sign out',
      'uploadDocument': 'Upload document',
      'localProcessing':
          'Images and PDFs are processed locally. Originals and the archive are not sent to Firebase.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pdfImage': 'PDF or image',
      'letterText': 'Letter text',
      'analyzeLetter': 'Analyze letter',
      'processing': 'AI is processing…',
      'newAnalysis': 'New analysis',
      'assistantTitle': 'AI assistant',
      'assistantHello':
          'Hello! Ask me about the most recently analyzed letter.',
      'assistantHint': 'For example: What is the deadline?',
      'onboardPhoto': 'Photograph a German letter',
      'onboardPhotoBody': 'Capture a document or upload a PDF or image.',
      'onboardAi': 'AI explains what it means',
      'onboardAiBody': 'A clear explanation in your language.',
      'onboardDeadline': 'Never miss a deadline',
      'onboardDeadlineBody': 'Receive reminders for important dates.',
      'next': 'Continue',
      'start': 'Start securely',
      'skip': 'Skip',
    },
    'bg': {
      'home': 'Начало',
      'archive': 'Архив',
      'assistant': 'Асистент',
      'profile': 'Профил',
      'welcome': 'Добре дошли',
      'homeSubtitle': 'Разбирайте немските писма на предпочитания от вас език.',
      'analyzeNew': 'Анализирай ново писмо',
      'remaining': 'Остават {count} от 2 безплатни анализа.',
      'unlimited': 'Premium анализите са активни.',
      'addDocument': 'Добави документ',
      'activatePremium': 'Активирай Premium',
      'recentLetters': 'Последни писма',
      'emptyLetters': 'Все още няма запазени писма.',
      'accountCta': 'Влезте или създайте акаунт',
      'accountCtaSubtitle': 'Акаунтът пази плана и отделния локален архив.',
      'appLanguage': 'Език на приложението',
      'signIn': 'Вход',
      'createAccount': 'Създай акаунт',
      'secureLetters': 'Акаунтът, планът и локалният архив остават отделни.',
      'email': 'Имейл',
      'password': 'Парола (поне 6 знака)',
      'continueGoogle': 'Продължи с Google',
      'continueApple': 'Продължи с Apple',
      'haveAccount': 'Имате акаунт? Влезте',
      'needAccount': 'Нямате акаунт? Регистрирайте се',
      'signInFailed': 'Входът е неуспешен',
      'myProfile': 'Моят профил',
      'preferredLanguage': 'Предпочитан език',
      'country': 'Държава на произход',
      'addCountry': 'Добавете държава на произход',
      'signInForProfile': 'Влезте, за да запазите профила',
      'signOut': 'Изход',
      'uploadDocument': 'Качете документ',
      'localProcessing':
          'Изображението или PDF се обработват локално. Оригиналът и архивът не се изпращат към Firebase.',
      'camera': 'Камера',
      'gallery': 'Галерия',
      'pdfImage': 'PDF или изображение',
      'letterText': 'Текст на писмото',
      'analyzeLetter': 'Анализирай писмо',
      'processing': 'AI обработва…',
      'newAnalysis': 'Нов анализ',
      'assistantTitle': 'AI асистент',
      'assistantHello':
          'Здравейте! Попитайте ме за последното анализирано писмо.',
      'assistantHint': 'Напр. Какъв е срокът?',
      'onboardPhoto': 'Снимайте немско писмо',
      'onboardPhotoBody': 'Снимайте документ или качете PDF/изображение.',
      'onboardAi': 'AI обяснява значението',
      'onboardAiBody': 'Ясно обяснение на вашия език.',
      'onboardDeadline': 'Не пропускайте срокове',
      'onboardDeadlineBody': 'Получавайте напомняния за важни дати.',
      'next': 'Продължи',
      'start': 'Започни сигурно',
      'skip': 'Пропусни',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) async => AppStrings(locale);

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
